"""
Phase 33.1 — Calculator Registry
Maps every calculator_key to its display metadata, category, automation tag,
and input field definitions used by the Risk Tool Picker.
"""

CALCULATOR_REGISTRY = {
    # ── CARDIOVASCULAR ──────────────────────────────────────────────
    'prevent': {
        'name': 'PREVENT — 10yr CVD Risk',
        'category': 'Cardiovascular',
        'automation_tag': 'auto_ehr',
        'type': 'regression',
        'status': 'ready',
        'description': 'AHA PREVENT equation for 10-year cardiovascular disease risk (Khan SS 2023).',
        'citation': 'Khan SS et al. Circulation. 2023;148(24):1982-2004.',
        'inputs': [
            {'key': 'age', 'label': 'Age', 'source': 'auto', 'type': 'number', 'min': 30, 'max': 79, 'required': True},
            {'key': 'sex', 'label': 'Biological Sex', 'source': 'auto', 'type': 'select', 'options': ['male', 'female'], 'required': True},
            {'key': 'total_cholesterol', 'label': 'Total Cholesterol (mg/dL)', 'source': 'auto', 'type': 'number', 'required': True},
            {'key': 'hdl', 'label': 'HDL-C (mg/dL)', 'source': 'auto', 'type': 'number', 'required': True},
            {'key': 'systolic_bp', 'label': 'Systolic BP (mmHg)', 'source': 'auto', 'type': 'number', 'required': True},
            {'key': 'egfr', 'label': 'eGFR (mL/min/1.73m²)', 'source': 'auto', 'type': 'number', 'required': False},
            {'key': 'has_diabetes', 'label': 'Diabetes', 'source': 'auto', 'type': 'boolean', 'required': False},
            {'key': 'smoking_status', 'label': 'Current Smoker', 'source': 'auto', 'type': 'select', 'options': ['never', 'former', 'current'], 'required': False},
            {'key': 'antihypertensive', 'label': 'On Antihypertensive', 'source': 'auto', 'type': 'boolean', 'required': False},
            {'key': 'statin', 'label': 'On Statin', 'source': 'auto', 'type': 'boolean', 'required': False},
        ],
        'interpretation': [
            {'label': 'Low', 'condition': '<5%', 'color': 'green'},
            {'label': 'Borderline', 'condition': '5-7.5%', 'color': 'yellow'},
            {'label': 'Intermediate', 'condition': '7.5-20%', 'color': 'orange'},
            {'label': 'High', 'condition': '≥20%', 'color': 'red'},
        ],
    },
    'bmi': {
        'name': 'BMI',
        'category': 'Metabolic',
        'automation_tag': 'auto_ehr',
        'type': 'formula',
        'status': 'ready',
        'description': 'Body Mass Index (kg/m² or 703×lb/in²).',
        'citation': 'WHO/NIH standard.',
        'inputs': [
            {'key': 'weight_lb', 'label': 'Weight (lbs)', 'source': 'auto', 'type': 'number', 'required': False},
            {'key': 'height_in', 'label': 'Height (inches)', 'source': 'auto', 'type': 'number', 'required': False},
            {'key': 'weight_kg', 'label': 'Weight (kg)', 'source': 'auto', 'type': 'number', 'required': False},
            {'key': 'height_m', 'label': 'Height (m)', 'source': 'auto', 'type': 'number', 'required': False},
        ],
        'interpretation': [
            {'label': 'Underweight', 'condition': '<18.5', 'color': 'yellow'},
            {'label': 'Normal', 'condition': '18.5-24.9', 'color': 'green'},
            {'label': 'Overweight', 'condition': '25-29.9', 'color': 'yellow'},
            {'label': 'Obesity Class I', 'condition': '30-34.9', 'color': 'orange'},
            {'label': 'Obesity Class II', 'condition': '35-39.9', 'color': 'red'},
            {'label': 'Obesity Class III', 'condition': '≥40', 'color': 'red'},
        ],
    },
    'ldl': {
        'name': 'LDL-C (Friedewald / Sampson)',
        'category': 'Metabolic',
        'automation_tag': 'auto_ehr',
        'type': 'formula',
        'status': 'ready',
        'description': 'Friedewald (TG<400) or Sampson 2020 (TG 400-800). Auto-selects.',
        'citation': 'Bhatt DL et al. JAMA 2022; Sampson M et al. JAMA Int Med 2020.',
        'inputs': [
            {'key': 'total_cholesterol', 'label': 'Total Cholesterol (mg/dL)', 'source': 'auto', 'type': 'number', 'required': True},
            {'key': 'hdl', 'label': 'HDL-C (mg/dL)', 'source': 'auto', 'type': 'number', 'required': True},
            {'key': 'triglycerides', 'label': 'Triglycerides (mg/dL)', 'source': 'auto', 'type': 'number', 'required': True},
        ],
        'interpretation': [
            {'label': 'Optimal', 'condition': '<100', 'color': 'green'},
            {'label': 'Near Optimal', 'condition': '100-129', 'color': 'green'},
            {'label': 'Borderline High', 'condition': '130-159', 'color': 'yellow'},
            {'label': 'High', 'condition': '160-189', 'color': 'orange'},
            {'label': 'Very High', 'condition': '190-219', 'color': 'red'},
            {'label': 'Severe', 'condition': '≥220', 'color': 'red'},
        ],
    },
    'pack_years': {
        'name': 'Pack Years',
        'category': 'Respiratory',
        'automation_tag': 'auto_ehr',
        'type': 'formula',
        'status': 'ready',
        'description': 'Cumulative tobacco exposure in pack-years (CPD/20 × years).',
        'citation': 'Standard clinical definition.',
        'inputs': [
            {'key': 'tobacco_status', 'label': 'Tobacco Status', 'source': 'auto', 'type': 'select', 'options': ['never', 'former', 'current'], 'required': True},
            {'key': 'tobacco_pack_years', 'label': 'Pack Years (if known)', 'source': 'auto', 'type': 'number', 'required': False},
            {'key': 'cigarettes_per_day', 'label': 'Cigarettes/Day', 'source': 'auto', 'type': 'number', 'required': False},
            {'key': 'years_smoked', 'label': 'Years Smoked', 'source': 'auto', 'type': 'number', 'required': False},
        ],
        'interpretation': [
            {'label': 'Never Smoker', 'condition': '0', 'color': 'green'},
            {'label': 'Light (<10 PY)', 'condition': '0.1-9.9', 'color': 'yellow'},
            {'label': 'Moderate (10-19 PY)', 'condition': '10-19.9', 'color': 'orange'},
            {'label': 'Heavy (≥20 PY)', 'condition': '≥20', 'color': 'red'},
        ],
    },
    'wells_dvt': {
        'name': 'Wells DVT Score',
        'category': 'Cardiovascular',
        'automation_tag': 'clinician',
        'type': 'rule_based',
        'status': 'ready',
        'description': 'Pre-test probability for deep vein thrombosis.',
        'citation': 'Wells PS et al. Lancet 1997.',
        'inputs': [
            {'key': 'active_cancer', 'label': 'Active cancer (treatment ≤6 mo)', 'source': 'clinician', 'type': 'boolean', 'points': 1},
            {'key': 'paralysis_paresis_plaster', 'label': 'Paralysis, paresis, or plaster immobilization', 'source': 'clinician', 'type': 'boolean', 'points': 1},
            {'key': 'bedridden_or_surgery', 'label': 'Bedridden ≥3d or major surgery ≤12 wk', 'source': 'clinician', 'type': 'boolean', 'points': 1},
            {'key': 'localized_tenderness_along_deep_venous_system', 'label': 'Localized tenderness along deep venous system', 'source': 'clinician', 'type': 'boolean', 'points': 1},
            {'key': 'entire_leg_swollen', 'label': 'Entire leg swollen', 'source': 'clinician', 'type': 'boolean', 'points': 1},
            {'key': 'calf_swelling_over_3_cm_vs_asymptomatic_leg', 'label': 'Calf swelling >3 cm vs asymptomatic side', 'source': 'clinician', 'type': 'boolean', 'points': 1},
            {'key': 'pitting_edema_confined_to_symptomatic_leg', 'label': 'Pitting edema confined to symptomatic leg', 'source': 'clinician', 'type': 'boolean', 'points': 1},
            {'key': 'collateral_superficial_veins', 'label': 'Collateral (non-varicose) superficial veins', 'source': 'clinician', 'type': 'boolean', 'points': 1},
            {'key': 'previously_documented_dvt', 'label': 'Previous documented DVT', 'source': 'clinician', 'type': 'boolean', 'points': 1},
            {'key': 'alternative_diagnosis_at_least_as_likely_as_dvt', 'label': 'Alternative diagnosis at least as likely', 'source': 'clinician', 'type': 'boolean', 'points': -2},
        ],
        'interpretation': [
            {'label': 'Low (D-dimer first)', 'condition': '≤0', 'color': 'green'},
            {'label': 'Moderate', 'condition': '1-2', 'color': 'yellow'},
            {'label': 'High (ultrasound)', 'condition': '≥3', 'color': 'red'},
        ],
    },
    'perc': {
        'name': 'PERC Rule (PE)',
        'category': 'Cardiovascular',
        'automation_tag': 'semi_auto',
        'type': 'rule_based',
        'status': 'ready',
        'description': 'Pulmonary Embolism Rule-out Criteria (ages <50, HR<100, SpO2≥95% auto-fill).',
        'citation': 'Kline JA et al. J Thromb Haemost 2004.',
        'inputs': [
            {'key': 'age_under_50', 'label': 'Age < 50', 'source': 'auto', 'type': 'boolean', 'excl': True},
            {'key': 'hr_under_100', 'label': 'HR < 100 bpm', 'source': 'auto', 'type': 'boolean', 'excl': True},
            {'key': 'spo2_95_or_above', 'label': 'SpO₂ ≥ 95%', 'source': 'auto', 'type': 'boolean', 'excl': True},
            {'key': 'no_hemoptysis', 'label': 'No hemoptysis', 'source': 'clinician', 'type': 'boolean', 'excl': True},
            {'key': 'no_estrogen_use', 'label': 'No estrogen use', 'source': 'clinician', 'type': 'boolean', 'excl': True},
            {'key': 'no_prior_dvt_pe', 'label': 'No prior DVT/PE', 'source': 'clinician', 'type': 'boolean', 'excl': True},
            {'key': 'no_unilateral_leg_swelling', 'label': 'No unilateral leg swelling', 'source': 'clinician', 'type': 'boolean', 'excl': True},
            {'key': 'no_surgery_trauma_4wk', 'label': 'No surgery/trauma in past 4 weeks', 'source': 'clinician', 'type': 'boolean', 'excl': True},
        ],
        'interpretation': [
            {'label': 'All PERC criteria met — PE ruled out', 'condition': 'all_true', 'color': 'green'},
            {'label': 'PERC not met — further workup needed', 'condition': 'any_false', 'color': 'red'},
        ],
    },
    # ── MENTAL HEALTH ────────────────────────────────────────────
    'gad7': {
        'name': 'GAD-7',
        'category': 'Mental Health',
        'automation_tag': 'patient_reported',
        'type': 'questionnaire',
        'status': 'ready',
        'description': 'Generalized Anxiety Disorder 7-item scale.',
        'citation': 'Spitzer RL et al. Arch Intern Med 2006.',
        'inputs': [
            {'key': 'item_1', 'label': 'Feeling nervous, anxious, or on edge', 'source': 'patient', 'type': 'likert4', 'required': True},
            {'key': 'item_2', 'label': 'Not able to stop or control worrying', 'source': 'patient', 'type': 'likert4', 'required': True},
            {'key': 'item_3', 'label': 'Worrying too much about different things', 'source': 'patient', 'type': 'likert4', 'required': True},
            {'key': 'item_4', 'label': 'Trouble relaxing', 'source': 'patient', 'type': 'likert4', 'required': True},
            {'key': 'item_5', 'label': 'So restless that it is hard to sit still', 'source': 'patient', 'type': 'likert4', 'required': True},
            {'key': 'item_6', 'label': 'Becoming easily annoyed or irritable', 'source': 'patient', 'type': 'likert4', 'required': True},
            {'key': 'item_7', 'label': 'Feeling afraid, as if something awful might happen', 'source': 'patient', 'type': 'likert4', 'required': True},
        ],
        'likert_labels': ['Not at all (0)', 'Several days (1)', 'More than half the days (2)', 'Nearly every day (3)'],
        'interpretation': [
            {'label': 'Minimal', 'condition': '0-4', 'color': 'green'},
            {'label': 'Mild', 'condition': '5-9', 'color': 'yellow'},
            {'label': 'Moderate', 'condition': '10-14', 'color': 'orange'},
            {'label': 'Severe', 'condition': '15-21', 'color': 'red'},
        ],
    },
    'gds15': {
        'name': 'GDS-15 (Geriatric Depression)',
        'category': 'Mental Health',
        'automation_tag': 'patient_reported',
        'type': 'questionnaire',
        'status': 'ready',
        'description': '15-item Geriatric Depression Scale (yes/no format).',
        'citation': 'Sheikh & Yesavage 1986.',
        'inputs': [
            {'key': 'item_1', 'label': 'Are you basically satisfied with your life?', 'source': 'patient', 'type': 'yesno_inv', 'required': True},
            {'key': 'item_2', 'label': 'Have you dropped many of your activities and interests?', 'source': 'patient', 'type': 'yesno', 'required': True},
            {'key': 'item_3', 'label': 'Do you feel that your life is empty?', 'source': 'patient', 'type': 'yesno', 'required': True},
            {'key': 'item_4', 'label': 'Do you often get bored?', 'source': 'patient', 'type': 'yesno', 'required': True},
            {'key': 'item_5', 'label': 'Are you in good spirits most of the time?', 'source': 'patient', 'type': 'yesno_inv', 'required': True},
            {'key': 'item_6', 'label': 'Are you afraid that something bad is going to happen to you?', 'source': 'patient', 'type': 'yesno', 'required': True},
            {'key': 'item_7', 'label': 'Do you feel happy most of the time?', 'source': 'patient', 'type': 'yesno_inv', 'required': True},
            {'key': 'item_8', 'label': 'Do you often feel helpless?', 'source': 'patient', 'type': 'yesno', 'required': True},
            {'key': 'item_9', 'label': 'Do you prefer to stay at home, rather than going out and doing new things?', 'source': 'patient', 'type': 'yesno', 'required': True},
            {'key': 'item_10', 'label': 'Do you feel you have more problems with memory than most?', 'source': 'patient', 'type': 'yesno', 'required': True},
            {'key': 'item_11', 'label': 'Do you think it is wonderful to be alive now?', 'source': 'patient', 'type': 'yesno_inv', 'required': True},
            {'key': 'item_12', 'label': 'Do you feel pretty worthless the way you are now?', 'source': 'patient', 'type': 'yesno', 'required': True},
            {'key': 'item_13', 'label': 'Do you feel full of energy?', 'source': 'patient', 'type': 'yesno_inv', 'required': True},
            {'key': 'item_14', 'label': 'Do you feel that your situation is hopeless?', 'source': 'patient', 'type': 'yesno', 'required': True},
            {'key': 'item_15', 'label': 'Do you think that most people are better off than you are?', 'source': 'patient', 'type': 'yesno', 'required': True},
        ],
        'interpretation': [
            {'label': 'Normal', 'condition': '0-5', 'color': 'green'},
            {'label': 'Mild Depression', 'condition': '6-10', 'color': 'yellow'},
            {'label': 'Severe Depression', 'condition': '11-15', 'color': 'red'},
        ],
    },
    'epds': {
        'name': 'EPDS (Perinatal Depression)',
        'category': 'Mental Health',
        'automation_tag': 'patient_reported',
        'type': 'questionnaire',
        'status': 'ready',
        'description': 'Edinburgh Postnatal Depression Scale — 10 items.',
        'citation': 'Cox JL et al. Br J Psychiatry 1987.',
        'inputs': [
            {'key': f'item_{i}', 'label': f'EPDS Item {i}', 'source': 'patient', 'type': 'epds', 'required': True}
            for i in range(1, 11)
        ],
        'likert_labels': ['As much as always (0)', 'Not quite so much (1)', 'Definitely not so much (2)', 'Not at all (3)'],
        'interpretation': [
            {'label': 'Normal', 'condition': '0-9', 'color': 'green'},
            {'label': 'Possible Depression', 'condition': '10-12', 'color': 'yellow'},
            {'label': 'Probable Depression', 'condition': '13+', 'color': 'red'},
        ],
    },
    'audit_c': {
        'name': 'AUDIT-C (Alcohol)',
        'category': 'Substance Use',
        'automation_tag': 'patient_reported',
        'type': 'questionnaire',
        'status': 'ready',
        'description': '3-item Alcohol Use Disorders Identification Test — Consumption.',
        'citation': 'Bush K et al. Arch Intern Med 1998.',
        'inputs': [
            {'key': 'item_1', 'label': 'How often do you have a drink containing alcohol?', 'source': 'patient', 'type': 'select',
             'options': ['Never (0)', 'Monthly or less (1)', '2-4 times/month (2)', '2-3 times/week (3)', '4+ times/week (4)'], 'required': True},
            {'key': 'item_2', 'label': 'How many drinks containing alcohol do you have on a typical day?', 'source': 'patient', 'type': 'select',
             'options': ['1-2 (0)', '3-4 (1)', '5-6 (2)', '7-9 (3)', '10+ (4)'], 'required': True},
            {'key': 'item_3', 'label': 'How often do you have 6 or more drinks on one occasion?', 'source': 'patient', 'type': 'select',
             'options': ['Never (0)', 'Less than monthly (1)', 'Monthly (2)', 'Weekly (3)', 'Daily or almost daily (4)'], 'required': True},
        ],
        'interpretation': [
            {'label': 'Low Risk (F)', 'condition': '<3 (female)', 'color': 'green'},
            {'label': 'Low Risk (M)', 'condition': '<4 (male)', 'color': 'green'},
            {'label': 'Positive Screen', 'condition': '≥3F / ≥4M', 'color': 'red'},
        ],
    },
    'cat': {
        'name': 'COPD Assessment Test (CAT)',
        'category': 'Respiratory',
        'automation_tag': 'patient_reported',
        'type': 'questionnaire',
        'status': 'ready',
        'description': 'COPD impact assessment — 8 items, 0-5 each.',
        'citation': 'Jones PW et al. Eur Respir J 2009.',
        'inputs': [
            {'key': f'item_{i}', 'label': f'CAT Item {i}', 'source': 'patient', 'type': 'likert6', 'required': True}
            for i in range(1, 9)
        ],
        'likert_labels': ['0', '1', '2', '3', '4', '5'],
        'interpretation': [
            {'label': 'Low Impact', 'condition': '0-10', 'color': 'green'},
            {'label': 'Medium Impact', 'condition': '11-20', 'color': 'yellow'},
            {'label': 'High Impact', 'condition': '21-30', 'color': 'orange'},
            {'label': 'Very High Impact', 'condition': '31-40', 'color': 'red'},
        ],
    },
    'mmrc': {
        'name': 'mMRC Dyspnea Scale',
        'category': 'Respiratory',
        'automation_tag': 'patient_reported',
        'type': 'questionnaire',
        'status': 'ready',
        'description': 'Modified MRC dyspnea scale — grade 0-4.',
        'citation': 'Mahler DA, Wells CK. Chest 1988.',
        'inputs': [
            {'key': 'item_1', 'label': 'mMRC Dyspnea Grade', 'source': 'patient', 'type': 'select',
             'options': ['0 — Dyspnea only with strenuous exercise', '1 — Dyspnea when hurrying on level or slight hill', '2 — Walks slower than people of same age due to dyspnea', '3 — Stops for breath after ~100m on flat', '4 — Too breathless to leave house / with dressing/undressing'], 'required': True},
        ],
        'interpretation': [
            {'label': 'Grade 0-1 (mild)', 'condition': '0-1', 'color': 'green'},
            {'label': 'Grade 2 (moderate)', 'condition': '2', 'color': 'yellow'},
            {'label': 'Grade 3-4 (severe)', 'condition': '3-4', 'color': 'red'},
        ],
    },
    'katz_adl': {
        'name': 'Katz ADL Index',
        'category': 'Functional',
        'automation_tag': 'clinician',
        'type': 'questionnaire',
        'status': 'ready',
        'description': 'Activities of Daily Living — 6 domains of independence.',
        'citation': 'Katz S. JAMA 1963.',
        'inputs': [
            {'key': 'bathing', 'label': 'Bathing', 'source': 'clinician', 'type': 'yesno_independent', 'required': True},
            {'key': 'dressing', 'label': 'Dressing', 'source': 'clinician', 'type': 'yesno_independent', 'required': True},
            {'key': 'toileting', 'label': 'Toileting', 'source': 'clinician', 'type': 'yesno_independent', 'required': True},
            {'key': 'transferring', 'label': 'Transferring', 'source': 'clinician', 'type': 'yesno_independent', 'required': True},
            {'key': 'continence', 'label': 'Continence', 'source': 'clinician', 'type': 'yesno_independent', 'required': True},
            {'key': 'feeding', 'label': 'Feeding', 'source': 'clinician', 'type': 'yesno_independent', 'required': True},
        ],
        'interpretation': [
            {'label': '6/6 — Independent', 'condition': '6', 'color': 'green'},
            {'label': '4-5 — Mild dependence', 'condition': '4-5', 'color': 'yellow'},
            {'label': '2-3 — Moderate dependence', 'condition': '2-3', 'color': 'orange'},
            {'label': '0-1 — Severe dependence', 'condition': '0-1', 'color': 'red'},
        ],
    },
    'crafft': {
        'name': 'CRAFFT (Adolescent Substance)',
        'category': 'Substance Use',
        'automation_tag': 'patient_reported',
        'type': 'questionnaire',
        'status': 'ready',
        'description': 'Substance use screening for adolescents (ages 14-21).',
        'citation': 'Knight JR et al. Arch Pediatr Adolesc Med 2002.',
        'inputs': [
            {'key': 'item_1', 'label': 'Have you ever ridden in a CAR driven by someone (incl. yourself) who was high/drunk?', 'source': 'patient', 'type': 'yesno', 'required': True},
            {'key': 'item_2', 'label': 'Do you use alcohol/drugs to RELAX, feel better about yourself, or fit in?', 'source': 'patient', 'type': 'yesno', 'required': True},
            {'key': 'item_3', 'label': 'Do you use alcohol/drugs when you are ALONE?', 'source': 'patient', 'type': 'yesno', 'required': True},
            {'key': 'item_4', 'label': 'Do you FORGET things you did while using alcohol/drugs?', 'source': 'patient', 'type': 'yesno', 'required': True},
            {'key': 'item_5', 'label': 'Do your family or FRIENDS tell you that you should cut down?', 'source': 'patient', 'type': 'yesno', 'required': True},
            {'key': 'item_6', 'label': 'Have you gotten into TROUBLE while using alcohol/drugs?', 'source': 'patient', 'type': 'yesno', 'required': True},
        ],
        'interpretation': [
            {'label': 'Low Risk', 'condition': '0-1', 'color': 'green'},
            {'label': 'High Risk — Brief Intervention', 'condition': '2-6', 'color': 'red'},
        ],
    },
    'ottawa_ankle': {
        'name': 'Ottawa Ankle Rules',
        'category': 'Musculoskeletal',
        'automation_tag': 'clinician',
        'type': 'rule_based',
        'status': 'ready',
        'description': 'Ankle x-ray decision rule after acute ankle injury.',
        'citation': 'Stiell IG et al. JAMA 1994.',
        'inputs': [
            {'key': 'bone_tenderness_posterior_lateral_malleolus', 'label': 'Bone tenderness along posterior lateral malleolus', 'source': 'clinician', 'type': 'boolean', 'points': 1},
            {'key': 'bone_tenderness_posterior_medial_malleolus', 'label': 'Bone tenderness along posterior medial malleolus', 'source': 'clinician', 'type': 'boolean', 'points': 1},
            {'key': 'unable_to_bear_weight', 'label': 'Unable to bear weight ×4 steps (immediate + in ED)', 'source': 'clinician', 'type': 'boolean', 'points': 1},
        ],
        'interpretation': [
            {'label': 'X-Ray Indicated', 'condition': 'any_positive', 'color': 'orange'},
            {'label': 'X-Ray Not Indicated', 'condition': 'all_negative', 'color': 'green'},
        ],
    },
    # ── RESTRICTED (licensed instruments — manual entry only) ───
    'phq9': {
        'name': 'PHQ-9 (Depression)',
        'category': 'Mental Health',
        'automation_tag': 'patient_reported',
        'type': 'questionnaire',
        'status': 'restricted_or_licensed',
        'description': 'Patient Health Questionnaire-9. Licensed instrument — manual score entry.',
        'citation': 'Kroenke K et al. J Gen Intern Med 2001.',
        'inputs': [
            {'key': 'total', 'label': 'Enter PHQ-9 total score (0-27)', 'source': 'manual', 'type': 'number', 'min': 0, 'max': 27, 'required': True},
        ],
        'interpretation': [
            {'label': 'Minimal', 'condition': '1-4', 'color': 'green'},
            {'label': 'Mild', 'condition': '5-9', 'color': 'yellow'},
            {'label': 'Moderate', 'condition': '10-14', 'color': 'orange'},
            {'label': 'Moderately Severe', 'condition': '15-19', 'color': 'red'},
            {'label': 'Severe', 'condition': '20-27', 'color': 'red'},
        ],
        'license_note': 'PHQ-9 is a licensed instrument by Pfizer. Obtain from official source.',
    },
    'moca': {
        'name': 'MoCA (Cognitive)',
        'category': 'Cognitive',
        'automation_tag': 'clinician',
        'type': 'questionnaire',
        'status': 'restricted_or_licensed',
        'description': 'Montreal Cognitive Assessment. Licensed — manual score entry.',
        'citation': 'Nasreddine ZS et al. J Am Geriatr Soc 2005.',
        'inputs': [
            {'key': 'total', 'label': 'Enter MoCA total score (0-30)', 'source': 'manual', 'type': 'number', 'min': 0, 'max': 30, 'required': True},
        ],
        'interpretation': [
            {'label': 'Normal', 'condition': '26-30', 'color': 'green'},
            {'label': 'Mild Cognitive Impairment', 'condition': '18-25', 'color': 'yellow'},
            {'label': 'Moderate Impairment', 'condition': '10-17', 'color': 'orange'},
            {'label': 'Severe Impairment', 'condition': '<10', 'color': 'red'},
        ],
        'license_note': 'MoCA is licensed. Use the official MoCA-Blind or in-person form.',
    },
    'stop_bang': {
        'name': 'STOP-BANG (OSA)',
        'category': 'Respiratory',
        'automation_tag': 'semi_auto',
        'type': 'rule_based',
        'status': 'ready',
        'description': 'Obstructive sleep apnea screening (BMI, age, sex auto-fill).',
        'citation': 'Chung F et al. Anesthesiology 2008.',
        'inputs': [
            {'key': 'snoring', 'label': 'Do you SNORE loudly?', 'source': 'clinician', 'type': 'boolean', 'points': 1},
            {'key': 'tired', 'label': 'Often TIRED, fatigued, or sleepy during daytime?', 'source': 'clinician', 'type': 'boolean', 'points': 1},
            {'key': 'observed_apnea', 'label': 'OBSERVED stop breathing during sleep?', 'source': 'clinician', 'type': 'boolean', 'points': 1},
            {'key': 'pressure', 'label': 'Do you have or are being treated for high blood PRESSURE?', 'source': 'auto', 'type': 'boolean', 'points': 1},
            {'key': 'bmi_over_35', 'label': 'BMI > 35?', 'source': 'auto', 'type': 'boolean', 'points': 1},
            {'key': 'age_over_50', 'label': 'AGE > 50 years?', 'source': 'auto', 'type': 'boolean', 'points': 1},
            {'key': 'neck_over_40', 'label': 'NECK circumference > 40 cm?', 'source': 'clinician', 'type': 'boolean', 'points': 1},
            {'key': 'male', 'label': 'GENDER = Male?', 'source': 'auto', 'type': 'boolean', 'points': 1},
        ],
        'interpretation': [
            {'label': 'Low OSA Risk', 'condition': '0-2', 'color': 'green'},
            {'label': 'Intermediate OSA Risk', 'condition': '3-4', 'color': 'yellow'},
            {'label': 'High OSA Risk', 'condition': '5-8', 'color': 'red'},
        ],
    },
    'airq': {
        'name': 'AIRQ (Asthma)',
        'category': 'Respiratory',
        'automation_tag': 'patient_reported',
        'type': 'questionnaire',
        'status': 'ready',
        'description': 'Asthma Impairment and Risk Questionnaire — 6 items.',
        'citation': 'Chipps BE et al. Allergy Asthma Proc 2017.',
        'inputs': [
            {'key': f'item_{i}', 'label': f'AIRQ Item {i}', 'source': 'patient', 'type': 'yesno', 'required': True}
            for i in range(1, 7)
        ],
        'interpretation': [
            {'label': 'Well Controlled', 'condition': '0-1', 'color': 'green'},
            {'label': 'Not Well Controlled', 'condition': '2-3', 'color': 'yellow'},
            {'label': 'Very Poorly Controlled', 'condition': '4-6', 'color': 'red'},
        ],
    },
    # ── SPECIAL: C-SSRS Suicidality Screening ──────────────
    'cssrs': {
        'name': 'C-SSRS (Suicidal Ideation Screening)',
        'category': 'Mental Health',
        'automation_tag': 'clinician',
        'type': 'questionnaire',
        'status': 'ready',
        'description': (
            'Columbia Suicide Severity Rating Scale — ideation intensity subscale. '
            'Q3-Q5 are shown only when Q2 is answered YES (branching logic).'
        ),
        'citation': 'Posner K et al. Am J Psychiatry 2011.',
        'inputs': [
            {'key': 'q1', 'label': 'Passive ideation: Wish to be dead or fall asleep and not wake up?',
             'source': 'clinician', 'type': 'yesno', 'required': True},
            {'key': 'q2', 'label': 'Active ideation: Non-specific suicidal thoughts ("I want to kill myself")?',
             'source': 'clinician', 'type': 'yesno', 'required': True},
            {'key': 'q3', 'label': 'Active ideation with some methods, without specific plan?',
             'source': 'clinician', 'type': 'yesno', 'required': False, 'branch_show': 'q2'},
            {'key': 'q4', 'label': 'Active ideation with some intent to act, without specific plan?',
             'source': 'clinician', 'type': 'yesno', 'required': False, 'branch_show': 'q2'},
            {'key': 'q5', 'label': 'Active ideation with specific plan and intent?',
             'source': 'clinician', 'type': 'yesno', 'required': False, 'branch_show': 'q2'},
            {'key': 'q6', 'label': 'Suicidal behavior in the past 3 months?',
             'source': 'clinician', 'type': 'yesno', 'required': True},
        ],
        'interpretation': [
            {'label': 'Low Risk', 'condition': 'all_negative', 'color': 'green'},
            {'label': 'Moderate Risk', 'condition': 'q1_or_q2', 'color': 'yellow'},
            {'label': 'High Risk', 'condition': 'q4_q5_or_q6', 'color': 'red'},
        ],
    },

    # ── SEMI-AUTO: Phase 37 additions ─────────────────────────────────────
    'pcp_hf': {
        'name': 'PCP-HF (Heart Failure Risk)',
        'category': 'Cardiovascular',
        'automation_tag': 'semi_auto',
        'type': 'formula',
        'status': 'ready',
        'description': 'Predicts 5-year risk of incident heart failure using 11 EHR-fillable inputs.',
        'citation': 'Pandey A et al. JACC Heart Fail 2018.',
        'inputs': [
            {'key': 'age', 'label': 'Age (years)', 'source': 'auto', 'type': 'number', 'required': True},
            {'key': 'sex', 'label': 'Sex', 'source': 'auto', 'type': 'select', 'options': ['male', 'female'], 'required': True},
            {'key': 'bmi', 'label': 'BMI (kg/m²)', 'source': 'auto', 'type': 'number', 'required': True},
            {'key': 'sbp', 'label': 'Systolic BP (mmHg)', 'source': 'auto', 'type': 'number', 'required': True},
            {'key': 'smoker', 'label': 'Current smoker', 'source': 'auto', 'type': 'boolean', 'required': True},
            {'key': 'glucose', 'label': 'Fasting glucose (mg/dL)', 'source': 'auto', 'type': 'number'},
            {'key': 'total_cholesterol', 'label': 'Total cholesterol (mg/dL)', 'source': 'auto', 'type': 'number'},
            {'key': 'hdl', 'label': 'HDL-C (mg/dL)', 'source': 'auto', 'type': 'number'},
            {'key': 'egfr', 'label': 'eGFR (mL/min/1.73m²)', 'source': 'auto', 'type': 'number'},
            {'key': 'bp_meds', 'label': 'On antihypertensive medications?', 'source': 'auto', 'type': 'boolean'},
            {'key': 'dm_meds', 'label': 'On diabetes medications?', 'source': 'auto', 'type': 'boolean'},
            {'key': 'qrs_duration', 'label': 'QRS duration (ms) — from ECG', 'source': 'clinician', 'type': 'number'},
        ],
        'interpretation': [
            {'label': 'Low Risk (<5%)', 'condition': '0-5', 'color': 'green'},
            {'label': 'Intermediate Risk (5-10%)', 'condition': '5-10', 'color': 'yellow'},
            {'label': 'High Risk (>10%)', 'condition': '10+', 'color': 'red'},
        ],
    },
    'ada_risk': {
        'name': 'ADA Diabetes Risk Test',
        'category': 'Metabolic',
        'automation_tag': 'semi_auto',
        'type': 'formula',
        'status': 'ready',
        'description': 'ADA 7-question risk test for undiagnosed type 2 diabetes. Age, sex, BMI, and hypertension auto-filled.',
        'citation': 'American Diabetes Association. Diabetes Care 1993.',
        'inputs': [
            {'key': 'age', 'label': 'Age (years)', 'source': 'auto', 'type': 'number', 'required': True},
            {'key': 'sex', 'label': 'Sex', 'source': 'auto', 'type': 'select', 'options': ['male', 'female'], 'required': True},
            {'key': 'bmi', 'label': 'BMI (kg/m²)', 'source': 'auto', 'type': 'number', 'required': True},
            {'key': 'hypertension', 'label': 'Has hypertension (diagnosed or SBP ≥ 140)?', 'source': 'auto', 'type': 'boolean', 'required': True},
            {'key': 'family_hx_dm', 'label': 'Parent, sibling, or child with diabetes?', 'source': 'clinician', 'type': 'boolean', 'required': True},
            {'key': 'physically_active', 'label': 'Physically active (exercise ≥ 3×/week)?', 'source': 'clinician', 'type': 'boolean', 'required': True},
            {'key': 'gestational_dm', 'label': 'Ever diagnosed with gestational diabetes? (women only)', 'source': 'clinician', 'type': 'boolean'},
        ],
        'interpretation': [
            {'label': 'Low Risk (0-4)', 'condition': '0-4', 'color': 'green'},
            {'label': 'Moderate Risk (5-6)', 'condition': '5-6', 'color': 'yellow'},
            {'label': 'High Risk (≥7)', 'condition': '7+', 'color': 'red'},
        ],
    },
    'aap_htn': {
        'name': 'AAP Pediatric Hypertension (≥13 yr)',
        'category': 'Cardiovascular',
        'automation_tag': 'semi_auto',
        'type': 'formula',
        'status': 'ready',
        'description': 'AAP 2017 guidelines: Stage 1 HTN ≥130/80, Stage 2 ≥140/90 for ages 13+. All inputs auto-filled from EHR.',
        'citation': 'Flynn JT et al. Pediatrics 2017.',
        'inputs': [
            {'key': 'sbp', 'label': 'Systolic BP (mmHg)', 'source': 'auto', 'type': 'number', 'required': True},
            {'key': 'dbp', 'label': 'Diastolic BP (mmHg)', 'source': 'auto', 'type': 'number', 'required': True},
            {'key': 'age', 'label': 'Age (years)', 'source': 'auto', 'type': 'number', 'required': True},
        ],
        'interpretation': [
            {'label': 'Normal (<130/<80)', 'condition': 'sbp<130_dbp<80', 'color': 'green'},
            {'label': 'Elevated (130-139/80-89)', 'condition': 'stage1', 'color': 'yellow'},
            {'label': 'Stage 2 HTN (≥140/≥90)', 'condition': 'stage2', 'color': 'red'},
        ],
    },
    'gail_model': {
        'name': 'Gail Model (Breast Cancer Risk)',
        'category': 'Preventive',
        'automation_tag': 'semi_auto',
        'type': 'formula',
        'status': 'blocked',
        'blocked_reason': 'Full Gail Model coefficients require NCI-licensed implementation. Age and sex are auto-filled; remaining inputs are manual.',
        'description': 'Estimates 5-year and lifetime risk of invasive breast cancer. Requires licensing for clinical use.',
        'citation': 'Gail MH et al. J Natl Cancer Inst 1989.',
        'inputs': [
            {'key': 'age', 'label': 'Age (years)', 'source': 'auto', 'type': 'number', 'required': True},
            {'key': 'race', 'label': 'Race/Ethnicity', 'source': 'auto', 'type': 'select', 'options': ['white', 'black', 'hispanic', 'asian', 'other'], 'required': True},
            {'key': 'menarche_age', 'label': 'Age at first menstrual period', 'source': 'clinician', 'type': 'number', 'required': True},
            {'key': 'first_birth_age', 'label': 'Age at first live birth (or 0 if nulliparous)', 'source': 'clinician', 'type': 'number', 'required': True},
            {'key': 'relatives_bc', 'label': 'First-degree relatives with breast cancer', 'source': 'clinician', 'type': 'number', 'required': True},
            {'key': 'biopsies', 'label': 'Number of prior breast biopsies', 'source': 'clinician', 'type': 'number', 'required': True},
            {'key': 'atypical_hyperplasia', 'label': 'Atypical hyperplasia on prior biopsy?', 'source': 'clinician', 'type': 'boolean'},
        ],
        'interpretation': [
            {'label': 'Low Risk (<1.67%)', 'condition': '0-1.67', 'color': 'green'},
            {'label': 'Elevated Risk (≥1.67%)', 'condition': '1.67+', 'color': 'red'},
        ],
    },
}

# Category grouping for the picker UI
CALCULATOR_CATEGORIES = [
    'Cardiovascular',
    'Metabolic',
    'Respiratory',
    'Mental Health',
    'Substance Use',
    'Cognitive',
    'Functional',
    'Musculoskeletal',
    'Preventive',
]

# Automation tag display labels
AUTOMATION_LABELS = {
    'auto_ehr': {'label': 'Auto', 'color': 'green', 'icon': '🟢'},
    'semi_auto': {'label': 'Semi-Auto', 'color': 'yellow', 'icon': '🟡'},
    'patient_reported': {'label': 'Patient', 'color': 'blue', 'icon': '🔵'},
    'clinician': {'label': 'Clinician', 'color': 'orange', 'icon': '🟠'},
}
