"""
data.py — All reference medical / demographic data for the patient generator.
No logic here — just structured lookup tables.
"""

# ---------------------------------------------------------------------------
# RELIGIONS
# ---------------------------------------------------------------------------
RELIGIONS = [
    "Christian – Protestant", "Christian – Catholic", "Christian – Baptist",
    "Christian – Methodist", "Christian – Lutheran", "Christian – Episcopal",
    "Christian – Pentecostal", "Christian – Seventh-day Adventist",
    "Christian – Orthodox", "Jewish – Reform", "Jewish – Conservative",
    "Jewish – Orthodox", "Muslim – Sunni", "Muslim – Shia",
    "Hindu", "Buddhist", "Sikh", "Jehovah's Witness",
    "Mormon / Latter-day Saint", "Unitarian Universalist",
    "Agnostic", "Atheist / No Religious Affiliation",
    "Spiritual but not religious", "Declined to specify", "Other",
]

# ---------------------------------------------------------------------------
# LANGUAGES
# ---------------------------------------------------------------------------
LANGUAGES = {
    "English": "en",
    "Spanish": "es",
    "Bilingual (English/Spanish)": "en,es",
    "Portuguese": "pt",
    "French": "fr",
    "Haitian Creole": "ht",
    "Vietnamese": "vi",
    "Mandarin": "zh",
    "Korean": "ko",
    "Arabic": "ar",
    "Hindi": "hi",
    "Tagalog": "tl",
    "Russian": "ru",
    "German": "de",
    "Japanese": "ja",
}

# ---------------------------------------------------------------------------
# NAME SUFFIXES / GENERATIONAL
# ---------------------------------------------------------------------------
GENERATIONAL_SUFFIXES = ["Jr.", "Sr.", "II", "III", "IV", "V", "VI", "VII", "VIII"]
PROFESSIONAL_SUFFIXES = []   # We don't put clinical credentials on test patients

# ---------------------------------------------------------------------------
# RACES / ETHNICITIES
# ---------------------------------------------------------------------------
RACES = [
    ("White", "2106-3"), ("Black or African American", "2054-5"),
    ("American Indian or Alaska Native", "1002-5"),
    ("Asian", "2028-9"), ("Native Hawaiian or Other Pacific Islander", "2076-8"),
    ("Hispanic or Latino", "2135-2"), ("Other", "2131-1"), ("Unknown", "UNK"),
]

# ---------------------------------------------------------------------------
# MARITAL STATUSES (HL7 codes)
# ---------------------------------------------------------------------------
MARITAL_STATUSES = [
    ("Single", "S"), ("Married", "M"), ("Divorced", "D"),
    ("Widowed", "W"), ("Separated", "L"), ("Common Law", "C"),
    ("Domestic Partner", "P"), ("Unknown", "UNK"),
]

# ---------------------------------------------------------------------------
# GENDER / SEX
# ---------------------------------------------------------------------------
BIOLOGICAL_SEX = [("Male", "M"), ("Female", "F")]
GENDER_IDENTITY = [
    ("Male", "446151000124109"), ("Female", "446141000124107"),
    ("Transgender Male", "407377005"), ("Transgender Female", "407376001"),
    ("Non-binary", "33791000087105"), ("Genderqueer", "446131000124102"),
    ("Prefer not to say", "UNK"),
]
SEXUAL_ORIENTATION = [
    ("Straight or Heterosexual", "20430005"),
    ("Gay or Lesbian", "38628009"),
    ("Bisexual", "42035005"),
    ("Prefer not to say", "UNK"),
]

# ---------------------------------------------------------------------------
# INSURANCE / PAYERS
# ---------------------------------------------------------------------------
PAYERS = [
    {"name": "Anthem Blue Cross Blue Shield", "type": "PPO"},
    {"name": "Aetna", "type": "HMO"},
    {"name": "UnitedHealthcare", "type": "PPO"},
    {"name": "Cigna", "type": "EPO"},
    {"name": "Humana", "type": "PPO"},
    {"name": "Medicare Part B", "type": "Fee-for-Service"},
    {"name": "Medicare Advantage (Humana)", "type": "HMO"},
    {"name": "Medicaid (Virginia)", "type": "Managed Care"},
    {"name": "Tricare Prime", "type": "HMO"},
    {"name": "Kaiser Permanente", "type": "HMO"},
    {"name": "Blue Cross Blue Shield of Virginia", "type": "PPO"},
    {"name": "Optima Health", "type": "HMO"},
    {"name": "Molina Healthcare", "type": "Medicaid HMO"},
    {"name": "Centene / WellCare", "type": "Medicaid HMO"},
    {"name": "Self-Pay / Uninsured", "type": "Self-Pay"},
    {"name": "Workers Compensation", "type": "Workers Comp"},
    {"name": "VA Community Care", "type": "VA"},
    {"name": "CHIP (Children's Health Insurance)", "type": "CHIP"},
]

# ---------------------------------------------------------------------------
# ALLERGIES
# ---------------------------------------------------------------------------
ALLERGIES = [
    {"name": "Penicillin", "rxnorm": "7980", "snomed": "372687004",
     "reactions": ["Hives", "Anaphylaxis", "Rash"],
     "severities": [("Severe", "24484000"), ("Moderate", "6736007")]},
    {"name": "Amoxicillin", "rxnorm": "723", "snomed": "372687004",
     "reactions": ["Rash", "Hives"],
     "severities": [("Mild", "255604002"), ("Moderate", "6736007")]},
    {"name": "Sulfonamides", "rxnorm": "10829", "snomed": "387406002",
     "reactions": ["Rash", "Steven-Johnson Syndrome"],
     "severities": [("Moderate", "6736007"), ("Severe", "24484000")]},
    {"name": "Codeine", "rxnorm": "2670", "snomed": "387494003",
     "reactions": ["Nausea", "Vomiting", "Respiratory depression"],
     "severities": [("Mild", "255604002"), ("Moderate", "6736007")]},
    {"name": "NSAIDs (ibuprofen, naproxen)", "rxnorm": "5640", "snomed": "372650005",
     "reactions": ["GI bleeding", "Renal impairment", "Rash"],
     "severities": [("Moderate", "6736007"), ("Severe", "24484000")]},
    {"name": "Latex", "rxnorm": "UNK", "snomed": "1003755004",
     "reactions": ["Contact dermatitis", "Anaphylaxis"],
     "severities": [("Moderate", "6736007"), ("Severe", "24484000")]},
    {"name": "Shellfish", "rxnorm": "UNK", "snomed": "735029006",
     "reactions": ["Anaphylaxis", "Hives", "Angioedema"],
     "severities": [("Severe", "24484000")]},
    {"name": "Peanuts", "rxnorm": "UNK", "snomed": "91935009",
     "reactions": ["Anaphylaxis", "Urticaria"],
     "severities": [("Severe", "24484000")]},
    {"name": "ACE Inhibitors", "rxnorm": "992731", "snomed": "372733002",
     "reactions": ["Cough", "Angioedema"],
     "severities": [("Mild", "255604002"), ("Moderate", "6736007")]},
    {"name": "Metformin", "rxnorm": "6809", "snomed": "372567009",
     "reactions": ["GI upset", "Lactic acidosis"],
     "severities": [("Mild", "255604002"), ("Severe", "24484000")]},
    {"name": "Aspirin", "rxnorm": "1191", "snomed": "387458008",
     "reactions": ["GI bleed", "Bronchospasm"],
     "severities": [("Moderate", "6736007"), ("Severe", "24484000")]},
    {"name": "Cephalosporins", "rxnorm": "UNK", "snomed": "373262009",
     "reactions": ["Cross-reactive rash"],
     "severities": [("Mild", "255604002"), ("Moderate", "6736007")]},
    {"name": "Fluoroquinolones", "rxnorm": "UNK", "snomed": "412070003",
     "reactions": ["Tendon rupture", "QT prolongation"],
     "severities": [("Moderate", "6736007"), ("Severe", "24484000")]},
    {"name": "Contrast Dye (iodine)", "rxnorm": "UNK", "snomed": "372913009",
     "reactions": ["Anaphylaxis", "Nephropathy"],
     "severities": [("Severe", "24484000")]},
    {"name": "Morphine", "rxnorm": "7052", "snomed": "373529000",
     "reactions": ["Itching", "Respiratory depression", "Nausea"],
     "severities": [("Moderate", "6736007"), ("Severe", "24484000")]},
]

# ---------------------------------------------------------------------------
# DIAGNOSES — organized by category
# Each: display, icd10, snomed (optional), category
# ---------------------------------------------------------------------------
DIAGNOSES = {
    "Cardiovascular": [
        ("Essential hypertension", "I10", "38341003"),
        ("Hypertensive heart disease with heart failure", "I11.0", "441481004"),
        ("Atrial fibrillation, unspecified", "I48.91", "49436004"),
        ("Atrial flutter", "I48.4", "56675007"),
        ("Heart failure with reduced ejection fraction", "I50.20", "703272007"),
        ("Heart failure with preserved ejection fraction", "I50.30", "703273002"),
        ("Coronary artery disease, native vessel", "I25.10", "53741008"),
        ("Acute myocardial infarction, anterior wall", "I21.09", "57054005"),
        ("History of myocardial infarction", "I25.2", "399211009"),
        ("Mitral valve regurgitation", "I34.0", "48724000"),
        ("Aortic stenosis", "I35.0", "60573004"),
        ("Deep vein thrombosis, lower extremity", "I82.401", "128053003"),
        ("Pulmonary embolism", "I26.99", "59282003"),
        ("Peripheral artery disease", "I70.219", "400047006"),
        ("Hyperlipidemia, mixed", "E78.2", "370992007"),
        ("Pure hypercholesterolemia", "E78.00", "13644009"),
        ("Cardiomyopathy, dilated", "I42.0", "195021004"),
        ("Ventricular tachycardia", "I47.2", "25569003"),
        ("Supraventricular tachycardia", "I47.1", "6456007"),
        ("Sick sinus syndrome", "I49.5", "60423000"),
        ("Pacemaker in situ", "Z95.0", "304339008"),
        ("Status post CABG", "Z95.1", "399261000"),
        ("Status post PCI / coronary stent", "Z95.5", "416940007"),
    ],
    "Pulmonary": [
        ("Moderate persistent asthma, uncomplicated", "J45.40", "195967001"),
        ("Severe persistent asthma with acute exacerbation", "J45.51", "233679003"),
        ("COPD with acute exacerbation", "J44.1", "195951007"),
        ("COPD, stable", "J44.0", "13645005"),
        ("Chronic bronchitis", "J42", "63480004"),
        ("Emphysema", "J43.9", "87433001"),
        ("Community-acquired pneumonia", "J18.9", "233604007"),
        ("COVID-19", "U07.1", "840539006"),
        ("Post-COVID-19 condition", "U09.9", "1119303003"),
        ("Obstructive sleep apnea", "G47.33", "78275009"),
        ("Pulmonary hypertension, primary", "I27.0", "11399002"),
        ("Interstitial lung disease", "J84.9", "51615001"),
        ("Pleural effusion", "J90", "60046008"),
        ("Pneumothorax", "J93.9", "36118008"),
        ("Acute respiratory failure", "J96.00", "65710008"),
        ("Influenza with pneumonia", "J11.00", "46999008"),
    ],
    "Endocrine / Metabolic": [
        ("Type 2 diabetes mellitus without complications", "E11.9", "44054006"),
        ("Type 2 DM with diabetic chronic kidney disease, stage 3", "E11.22", "421893009"),
        ("Type 2 DM with diabetic polyneuropathy", "E11.40", "140101000119109"),
        ("Type 2 DM with diabetic macular edema", "E11.311", "313436004"),
        ("Type 1 diabetes mellitus without complications", "E10.9", "46635009"),
        ("Hypothyroidism, unspecified", "E03.9", "40930008"),
        ("Hyperthyroidism / Graves disease", "E05.00", "353295004"),
        ("Hashimoto thyroiditis", "E06.3", "21983002"),
        ("Metabolic syndrome", "E88.81", "237602007"),
        ("Obesity, BMI 30–34.9", "E66.09", "414915002"),
        ("Morbid obesity, BMI ≥40", "E66.01", "238136002"),
        ("Hypoglycemia, unspecified", "E16.0", "302866003"),
        ("Cushing syndrome", "E24.9", "190502001"),
        ("Addison disease", "E27.1", "363732003"),
        ("Vitamin D deficiency", "E55.9", "34713006"),
        ("Gout, unspecified joint", "M10.9", "90560007"),
        ("Hyperuricemia without gout", "E79.0", "35885006"),
    ],
    "Renal": [
        ("Chronic kidney disease, stage 1", "N18.1", "431855005"),
        ("Chronic kidney disease, stage 2", "N18.2", "431856006"),
        ("Chronic kidney disease, stage 3a", "N18.31", "700379002"),
        ("Chronic kidney disease, stage 4", "N18.4", "431857002"),
        ("End-stage renal disease on dialysis", "N18.6", "46177005"),
        ("Acute kidney injury", "N17.9", "14669001"),
        ("Nephrotic syndrome", "N04.9", "52254009"),
        ("Nephrolithiasis (kidney stones)", "N20.0", "95570007"),
        ("Urinary tract infection", "N39.0", "431308006"),
        ("Recurrent UTIs", "N39.0", "197927001"),
        ("Benign prostatic hyperplasia with LUTS", "N40.1", "266569009"),
        ("Prostatitis", "N41.9", "9713002"),
        ("Neurogenic bladder", "N31.9", "397732007"),
    ],
    "Gastrointestinal": [
        ("Gastroesophageal reflux disease without esophagitis", "K21.9", "235595009"),
        ("GERD with esophagitis", "K21.0", "17082002"),
        ("Barrett esophagus", "K22.70", "302914006"),
        ("Peptic ulcer disease, gastric", "K25.9", "53907002"),
        ("Helicobacter pylori gastritis", "K29.60", "397825002"),
        ("Irritable bowel syndrome with diarrhea", "K58.0", "10743008"),
        ("Crohn disease of small intestine", "K50.00", "34000006"),
        ("Ulcerative colitis, extensive", "K51.40", "64766004"),
        ("Diverticulosis of colon", "K57.30", "397881000"),
        ("Diverticulitis, colon", "K57.32", "78574002"),
        ("Celiac disease", "K90.0", "396331005"),
        ("Fatty liver disease (NAFLD)", "K76.0", "197321007"),
        ("Alcoholic cirrhosis of liver", "K70.30", "307641005"),
        ("Primary biliary cholangitis", "K74.3", "31712002"),
        ("Cholelithiasis (gallstones)", "K80.20", "235919008"),
        ("Pancreatitis, chronic", "K86.1", "235494005"),
        ("Colorectal cancer", "C18.9", "363406005"),
        ("Hepatocellular carcinoma", "C22.0", "25370001"),
    ],
    "Musculoskeletal": [
        ("Osteoarthritis, knee", "M17.9", "57773001"),
        ("Osteoarthritis, hip", "M16.9", "22253000"),
        ("Osteoarthritis, lumbar spine", "M47.816", "270427003"),
        ("Rheumatoid arthritis, seropositive", "M05.9", "69896004"),
        ("Systemic lupus erythematosus", "M32.9", "55464009"),
        ("Fibromyalgia", "M79.3", "24693007"),
        ("Osteoporosis with pathological fracture, vertebra", "M80.08XA", "203438001"),
        ("Osteoporosis without fracture", "M81.0", "64859006"),
        ("Ankylosing spondylitis", "M45.9", "9631008"),
        ("Psoriatic arthritis", "L40.50", "33339001"),
        ("Low back pain, acute", "M54.5", "279039007"),
        ("Lumbar radiculopathy", "M54.4", "128196005"),
        ("Rotator cuff tear", "M75.1", "307731004"),
        ("Carpal tunnel syndrome", "G56.00", "57406009"),
        ("Plantar fasciitis", "M72.2", "36047009"),
    ],
    "Neurological": [
        ("Migraine without aura, not intractable", "G43.009", "37796009"),
        ("Migraine with aura", "G43.109", "56097005"),
        ("Epilepsy, focal without loss of consciousness", "G40.109", "313307000"),
        ("Generalized epilepsy", "G40.309", "230436006"),
        ("Ischemic stroke (CVA)", "I63.9", "422504002"),
        ("TIA (transient ischemic attack)", "G45.9", "266257000"),
        ("Parkinson disease", "G20", "49049000"),
        ("Alzheimer dementia, mild", "G30.0", "26929004"),
        ("Vascular dementia", "F01.50", "429998004"),
        ("Multiple sclerosis, relapsing-remitting", "G35", "26889001"),
        ("Peripheral neuropathy, diabetic", "E11.40", "230572002"),
        ("Essential tremor", "G25.0", "609558009"),
        ("Bell palsy", "G51.0", "51651009"),
        ("Restless legs syndrome", "G25.81", "32914008"),
        ("Guillain-Barré syndrome", "G61.0", "40956001"),
        ("Myasthenia gravis", "G70.00", "91637004"),
        ("ALS (Amyotrophic lateral sclerosis)", "G12.21", "86044005"),
    ],
    "Psychiatric / Behavioral": [
        ("Major depressive disorder, single episode, moderate", "F32.1", "310495003"),
        ("Major depressive disorder, recurrent, severe without psychosis", "F33.2", "191616008"),
        ("Generalized anxiety disorder", "F41.1", "21897009"),
        ("Panic disorder without agoraphobia", "F41.0", "371631005"),
        ("PTSD", "F43.10", "47505003"),
        ("Bipolar I disorder, current manic", "F31.10", "13746004"),
        ("Bipolar II disorder", "F31.81", "191590005"),
        ("Schizophrenia, paranoid type", "F20.0", "191526005"),
        ("Schizoaffective disorder", "F25.9", "68890003"),
        ("ADHD, combined type", "F90.2", "406506008"),
        ("Autism spectrum disorder", "F84.0", "408856003"),
        ("OCD", "F42.9", "191736004"),
        ("Anorexia nervosa", "F50.00", "56882008"),
        ("Bulimia nervosa", "F50.2", "78004001"),
        ("Alcohol use disorder, moderate", "F10.20", "66214007"),
        ("Opioid use disorder", "F11.20", "75544000"),
        ("Cannabis use disorder", "F12.20", "37344009"),
        ("Insomnia disorder", "G47.00", "193462001"),
        ("Borderline personality disorder", "F60.3", "20010003"),
    ],
    "Infectious Disease": [
        ("HIV infection, asymptomatic", "B20", "165816005"),
        ("HIV / AIDS", "B20", "86406008"),
        ("Chronic hepatitis B", "B18.1", "10295004"),
        ("Chronic hepatitis C", "B18.2", "128302006"),
        ("Latent tuberculosis", "Z22.7", "28283008"),
        ("Cellulitis of lower leg", "L03.115", "128045006"),
        ("MRSA infection", "A49.02", "115329001"),
        ("Sepsis due to Staphylococcus aureus", "A41.01", "447526004"),
        ("Recurrent C. diff colitis", "A04.72", "425464007"),
        ("Lyme disease", "A69.20", "23502006"),
        ("Mononucleosis (EBV)", "B27.00", "271558008"),
        ("Herpes zoster (shingles)", "B02.9", "4740000"),
        ("Genital herpes simplex, recurrent", "A60.09", "33839006"),
        ("Syphilis, primary", "A51.0", "186847001"),
        ("Gonorrhea", "A54.9", "15628003"),
        ("Chlamydia", "A74.9", "240589008"),
    ],
    "Oncology": [
        ("Breast cancer, right, stage II", "C50.911", "188161004"),
        ("Breast cancer in situ (DCIS)", "D05.10", "73505005"),
        ("Lung cancer, NSCLC, stage III", "C34.10", "254637007"),
        ("Prostate cancer, localized", "C61", "399068003"),
        ("Colorectal cancer, sigmoid", "C18.7", "363406005"),
        ("Non-Hodgkin lymphoma, diffuse large B-cell", "C83.30", "413448000"),
        ("Hodgkin lymphoma", "C81.90", "118599009"),
        ("Leukemia, CLL", "C91.10", "51092000"),
        ("Melanoma, upper back", "C43.59", "372244006"),
        ("Basal cell carcinoma", "C44.91", "413448000"),
        ("Ovarian cancer, stage III", "C56.9", "363353009"),
        ("Cervical cancer in situ", "D06.9", "363354003"),
        ("Thyroid cancer, papillary", "C73", "363478007"),
        ("Bladder cancer", "C67.9", "363422002"),
        ("Pancreatic cancer", "C25.9", "363418001"),
        ("Leukemia, AML", "C91.00", "413448000"),
        ("Multiple myeloma", "C90.00", "109989006"),
        ("Glioblastoma", "C71.9", "393563007"),
        ("Colon cancer, personal history of", "Z85.038", "315058002"),
    ],
    "Dermatology": [
        ("Plaque psoriasis", "L40.0", "9014002"),
        ("Atopic dermatitis (eczema)", "L20.9", "24079001"),
        ("Acne vulgaris", "L70.0", "11381005"),
        ("Rosacea", "L71.9", "398909004"),
        ("Seborrheic dermatitis", "L21.9", "50563003"),
        ("Contact dermatitis", "L25.9", "40275004"),
        ("Urticaria (hives), chronic", "L50.9", "126485001"),
        ("Hidradenitis suppurativa", "L73.2", "59393003"),
        ("Alopecia areata", "L63.9", "68225006"),
        ("Herpes zoster rash", "B02.9", "4740000"),
        ("Tinea pedis (athlete's foot)", "B35.3", "6020002"),
        ("Nail fungal infection (onychomycosis)", "B35.1", "414941008"),
    ],
    "Obstetrics / Gynecology": [
        ("Irregular menstruation", "N92.6", "80182007"),
        ("Endometriosis", "N80.9", "129103003"),
        ("Polycystic ovary syndrome (PCOS)", "E28.2", "69878008"),
        ("Uterine fibroids (leiomyoma)", "D25.9", "95315005"),
        ("Menopause, natural", "N95.1", "76498008"),
        ("Premature ovarian failure", "E28.310", "237862000"),
        ("Gestational diabetes, diet controlled", "O24.410", "11687002"),
        ("Pre-eclampsia, severe", "O14.10", "46764007"),
        ("Recurrent pregnancy loss", "N96", "17369002"),
        ("Pelvic inflammatory disease", "N73.9", "198130006"),
        ("Cervical dysplasia (CIN II)", "N87.1", "285838002"),
        ("Ovarian cyst", "N83.209", "79031000"),
        ("Ectopic pregnancy (resolved)", "Z87.59", "34801009"),
    ],
    "Pediatric / Developmental": [
        ("Well child visit, age 2 months", "Z00.121", "170099002"),
        ("Acute otitis media", "H66.90", "3110003"),
        ("Otitis media with effusion (glue ear)", "H65.90", "68996008"),
        ("Group A strep pharyngitis", "J02.0", "43878008"),
        ("RSV bronchiolitis", "J21.0", "4120002"),
        ("Failure to thrive, infant", "P92.6", "41323004"),
        ("Febrile seizure, simple", "R56.00", "41497008"),
        ("Kawasaki disease", "M30.3", "75053002"),
        ("Congenital heart disease, VSD", "Q21.0", "30288003"),
        ("Congenital hypothyroidism", "E03.1", "36138009"),
        ("Down syndrome (Trisomy 21)", "Q90.9", "41040004"),
        ("Cerebral palsy, spastic diplegic", "G80.1", "61920004"),
        ("Developmental delay, speech/language", "F80.9", "162992003"),
        ("ADHD, predominantly inattentive type", "F90.0", "406506008"),
    ],
    "Geriatric": [
        ("Falls, recurrent", "R55", "161898004"),
        ("Dementia with behavioral disturbance", "F03.90", "52448006"),
        ("Sarcopenia", "M62.84", "415510000"),
        ("Pressure ulcer, stage II, sacral", "L89.152", "26711005"),
        ("Malnutrition, mild", "E44.1", "65404009"),
        ("Frailty syndrome", "R54", "248279007"),
        ("Hearing loss, presbycusis", "H91.10", "49526009"),
        ("Macular degeneration, dry AMD", "H35.31", "267718000"),
        ("Cataracts", "H26.9", "193570009"),
        ("Urinary incontinence, stress", "N39.3", "165232002"),
        ("Functional decline, post-hospitalization", "Z74.09", "160685001"),
    ],
}

# Flatten for random selection
ALL_DIAGNOSES = []
for cat, items in DIAGNOSES.items():
    for item in items:
        ALL_DIAGNOSES.append({"display": item[0], "icd10": item[1],
                               "snomed": item[2], "category": cat})

# ---------------------------------------------------------------------------
# MEDICATIONS — name, rxnorm, generic, typical_sig, dose_unit
# ---------------------------------------------------------------------------
MEDICATIONS = [
    # Antihypertensives
    {"name": "Lisinopril 10 mg tablet", "rxnorm": "314076", "generic": "lisinopril",
     "sig": "Take 1 tablet by mouth once daily", "dose": "10", "unit": "mg", "qty": 30, "rf": 11},
    {"name": "Lisinopril 20 mg tablet", "rxnorm": "314077", "generic": "lisinopril",
     "sig": "Take 1 tablet by mouth once daily", "dose": "20", "unit": "mg", "qty": 30, "rf": 11},
    {"name": "Amlodipine 5 mg tablet", "rxnorm": "197361", "generic": "amlodipine",
     "sig": "Take 1 tablet by mouth once daily", "dose": "5", "unit": "mg", "qty": 30, "rf": 11},
    {"name": "Amlodipine 10 mg tablet", "rxnorm": "329526", "generic": "amlodipine",
     "sig": "Take 1 tablet by mouth once daily", "dose": "10", "unit": "mg", "qty": 30, "rf": 11},
    {"name": "Metoprolol succinate 50 mg tablet ER", "rxnorm": "866514", "generic": "metoprolol succinate",
     "sig": "Take 1 tablet by mouth once daily", "dose": "50", "unit": "mg", "qty": 30, "rf": 11},
    {"name": "Carvedilol 12.5 mg tablet", "rxnorm": "200801", "generic": "carvedilol",
     "sig": "Take 1 tablet by mouth twice daily with meals", "dose": "12.5", "unit": "mg", "qty": 60, "rf": 5},
    {"name": "Losartan 50 mg tablet", "rxnorm": "979492", "generic": "losartan",
     "sig": "Take 1 tablet by mouth once daily", "dose": "50", "unit": "mg", "qty": 30, "rf": 11},
    {"name": "Valsartan 160 mg tablet", "rxnorm": "349201", "generic": "valsartan",
     "sig": "Take 1 tablet by mouth once daily", "dose": "160", "unit": "mg", "qty": 30, "rf": 5},
    {"name": "Hydrochlorothiazide 25 mg tablet", "rxnorm": "310798", "generic": "hydrochlorothiazide",
     "sig": "Take 1 tablet by mouth once daily in the morning", "dose": "25", "unit": "mg", "qty": 30, "rf": 11},
    {"name": "Furosemide 40 mg tablet", "rxnorm": "310429", "generic": "furosemide",
     "sig": "Take 1 tablet by mouth twice daily", "dose": "40", "unit": "mg", "qty": 60, "rf": 5},
    {"name": "Spironolactone 25 mg tablet", "rxnorm": "317372", "generic": "spironolactone",
     "sig": "Take 1 tablet by mouth once daily", "dose": "25", "unit": "mg", "qty": 30, "rf": 5},
    {"name": "Clonidine 0.1 mg tablet", "rxnorm": "197741", "generic": "clonidine",
     "sig": "Take 1 tablet by mouth twice daily", "dose": "0.1", "unit": "mg", "qty": 60, "rf": 5},
    # Statins / Lipid-lowering
    {"name": "Atorvastatin 40 mg tablet", "rxnorm": "617311", "generic": "atorvastatin",
     "sig": "Take 1 tablet by mouth once daily at bedtime", "dose": "40", "unit": "mg", "qty": 30, "rf": 11},
    {"name": "Atorvastatin 80 mg tablet", "rxnorm": "259255", "generic": "atorvastatin",
     "sig": "Take 1 tablet by mouth once daily at bedtime", "dose": "80", "unit": "mg", "qty": 30, "rf": 11},
    {"name": "Rosuvastatin 20 mg tablet", "rxnorm": "904458", "generic": "rosuvastatin",
     "sig": "Take 1 tablet by mouth once daily", "dose": "20", "unit": "mg", "qty": 30, "rf": 11},
    {"name": "Simvastatin 40 mg tablet", "rxnorm": "312961", "generic": "simvastatin",
     "sig": "Take 1 tablet by mouth once daily at bedtime", "dose": "40", "unit": "mg", "qty": 30, "rf": 11},
    {"name": "Ezetimibe 10 mg tablet", "rxnorm": "341248", "generic": "ezetimibe",
     "sig": "Take 1 tablet by mouth once daily", "dose": "10", "unit": "mg", "qty": 30, "rf": 5},
    {"name": "Fenofibrate 145 mg tablet", "rxnorm": "606253", "generic": "fenofibrate",
     "sig": "Take 1 tablet by mouth once daily with food", "dose": "145", "unit": "mg", "qty": 30, "rf": 5},
    # Diabetes
    {"name": "Metformin HCl 1000 mg tablet", "rxnorm": "861007", "generic": "metformin",
     "sig": "Take 1 tablet by mouth twice daily with meals", "dose": "1000", "unit": "mg", "qty": 60, "rf": 11},
    {"name": "Metformin HCl 500 mg tablet", "rxnorm": "861005", "generic": "metformin",
     "sig": "Take 1 tablet by mouth twice daily with meals", "dose": "500", "unit": "mg", "qty": 60, "rf": 11},
    {"name": "Glipizide 10 mg tablet", "rxnorm": "310488", "generic": "glipizide",
     "sig": "Take 1 tablet by mouth once daily before breakfast", "dose": "10", "unit": "mg", "qty": 30, "rf": 5},
    {"name": "Jardiance 10 mg tablet", "rxnorm": "1545653", "generic": "empagliflozin",
     "sig": "Take 1 tablet by mouth once daily in the morning", "dose": "10", "unit": "mg", "qty": 30, "rf": 11},
    {"name": "Farxiga 10 mg tablet", "rxnorm": "1488574", "generic": "dapagliflozin",
     "sig": "Take 1 tablet by mouth once daily in the morning", "dose": "10", "unit": "mg", "qty": 30, "rf": 11},
    {"name": "Ozempic 0.5 mg/dose pen injector", "rxnorm": "2200\x34", "generic": "semaglutide (diabetes)",
     "sig": "Inject 0.5 mg subcutaneously once weekly", "dose": "0.5", "unit": "mg", "qty": 4, "rf": 3},
    {"name": "Trulicity 1.5 mg/0.5 mL pen injector", "rxnorm": "1534763", "generic": "dulaglutide",
     "sig": "Inject 1.5 mg subcutaneously once weekly", "dose": "1.5", "unit": "mg", "qty": 4, "rf": 3},
    {"name": "Januvia 100 mg tablet", "rxnorm": "2709603", "generic": "sitagliptin",
     "sig": "Take 1 tablet by mouth once daily", "dose": "100", "unit": "mg", "qty": 30, "rf": 5},
    {"name": "Lantus (insulin glargine) 100 unit/mL vial", "rxnorm": "274783", "generic": "insulin glargine",
     "sig": "Inject 20 units subcutaneously once daily at bedtime", "dose": "20", "unit": "units", "qty": 3, "rf": 5},
    {"name": "Novolog (insulin aspart) 100 unit/mL vial", "rxnorm": "1151132", "generic": "insulin aspart",
     "sig": "Inject 4–10 units subcutaneously with each meal per sliding scale", "dose": "10", "unit": "units", "qty": 3, "rf": 5},
    {"name": "Wegovy 0.25 mg/0.5 mL pen injector", "rxnorm": "2553501", "generic": "semaglutide (weight loss)",
     "sig": "Inject 0.25 mg subcutaneously once weekly for 4 weeks", "dose": "0.25", "unit": "mg", "qty": 4, "rf": 3},
    # Anticoagulants
    {"name": "Warfarin 5 mg tablet", "rxnorm": "855332", "generic": "warfarin",
     "sig": "Take as directed per INR dosing schedule", "dose": "5", "unit": "mg", "qty": 30, "rf": 11},
    {"name": "Eliquis 5 mg tablet", "rxnorm": "1364435", "generic": "apixaban",
     "sig": "Take 1 tablet by mouth twice daily", "dose": "5", "unit": "mg", "qty": 60, "rf": 11},
    {"name": "Xarelto 20 mg tablet", "rxnorm": "1157702", "generic": "rivaroxaban",
     "sig": "Take 1 tablet by mouth once daily with the evening meal", "dose": "20", "unit": "mg", "qty": 30, "rf": 11},
    {"name": "Aspirin 81 mg tablet", "rxnorm": "243670", "generic": "aspirin",
     "sig": "Take 1 tablet by mouth once daily", "dose": "81", "unit": "mg", "qty": 30, "rf": 11},
    {"name": "Aspirin 325 mg tablet", "rxnorm": "1191", "generic": "aspirin",
     "sig": "Take 1 tablet by mouth once daily", "dose": "325", "unit": "mg", "qty": 30, "rf": 11},
    {"name": "Clopidogrel 75 mg tablet", "rxnorm": "309362", "generic": "clopidogrel",
     "sig": "Take 1 tablet by mouth once daily", "dose": "75", "unit": "mg", "qty": 30, "rf": 11},
    # GI
    {"name": "Omeprazole 20 mg delayed-release capsule", "rxnorm": "40790", "generic": "omeprazole",
     "sig": "Take 1 capsule by mouth once daily before breakfast", "dose": "20", "unit": "mg", "qty": 30, "rf": 11},
    {"name": "Pantoprazole 40 mg tablet", "rxnorm": "261455", "generic": "pantoprazole",
     "sig": "Take 1 tablet by mouth once daily 30 minutes before a meal", "dose": "40", "unit": "mg", "qty": 30, "rf": 11},
    {"name": "Ondansetron 4 mg tablet", "rxnorm": "312087", "generic": "ondansetron",
     "sig": "Take 1 tablet by mouth every 8 hours as needed for nausea", "dose": "4", "unit": "mg", "qty": 12, "rf": 2},
    {"name": "Dicyclomine 20 mg capsule", "rxnorm": "310276", "generic": "dicyclomine",
     "sig": "Take 1 capsule by mouth four times daily before meals and at bedtime", "dose": "20", "unit": "mg", "qty": 120, "rf": 5},
    {"name": "Mesalamine 400 mg DR tablet", "rxnorm": "309951", "generic": "mesalamine",
     "sig": "Take 2 tablets by mouth three times daily", "dose": "400", "unit": "mg", "qty": 180, "rf": 11},
    # Pulmonary
    {"name": "Albuterol HFA 90 mcg/actuation aerosol inhaler", "rxnorm": "745679", "generic": "albuterol",
     "sig": "Inhale 2 puffs by mouth every 4-6 hours as needed for shortness of breath or wheezing", "dose": "180", "unit": "mcg", "qty": 1, "rf": 3},
    {"name": "Fluticasone-salmeterol 250-50 diskus inhaler", "rxnorm": "896245", "generic": "fluticasone/salmeterol",
     "sig": "Inhale 1 puff by mouth twice daily", "dose": "250/50", "unit": "mcg", "qty": 1, "rf": 3},
    {"name": "Tiotropium 18 mcg capsule for inhalation", "rxnorm": "861901", "generic": "tiotropium",
     "sig": "Inhale contents of 1 capsule by mouth once daily using HandiHaler device", "dose": "18", "unit": "mcg", "qty": 30, "rf": 3},
    {"name": "Montelukast 10 mg tablet", "rxnorm": "703994", "generic": "montelukast",
     "sig": "Take 1 tablet by mouth once daily in the evening", "dose": "10", "unit": "mg", "qty": 30, "rf": 5},
    {"name": "Prednisone 40 mg tablet", "rxnorm": "763179", "generic": "prednisone",
     "sig": "Take 1 tablet by mouth once daily for 5 days then stop — do not abruptly discontinue", "dose": "40", "unit": "mg", "qty": 5, "rf": 0},
    {"name": "Budesonide/formoterol 160-4.5 mcg inhaler", "rxnorm": "896209", "generic": "budesonide/formoterol",
     "sig": "Inhale 2 puffs by mouth twice daily", "dose": "160/4.5", "unit": "mcg", "qty": 1, "rf": 3},
    # Psychiatric
    {"name": "Sertraline 100 mg tablet", "rxnorm": "312940", "generic": "sertraline",
     "sig": "Take 1 tablet by mouth once daily in the morning", "dose": "100", "unit": "mg", "qty": 30, "rf": 5},
    {"name": "Escitalopram 20 mg tablet", "rxnorm": "596926", "generic": "escitalopram",
     "sig": "Take 1 tablet by mouth once daily", "dose": "20", "unit": "mg", "qty": 30, "rf": 5},
    {"name": "Fluoxetine 40 mg capsule", "rxnorm": "197803", "generic": "fluoxetine",
     "sig": "Take 1 capsule by mouth once daily in the morning", "dose": "40", "unit": "mg", "qty": 30, "rf": 5},
    {"name": "Duloxetine 60 mg delayed-release capsule", "rxnorm": "596928", "generic": "duloxetine",
     "sig": "Take 1 capsule by mouth once daily", "dose": "60", "unit": "mg", "qty": 30, "rf": 5},
    {"name": "Bupropion XL 300 mg tablet", "rxnorm": "993503", "generic": "bupropion",
     "sig": "Take 1 tablet by mouth once daily in the morning", "dose": "300", "unit": "mg", "qty": 30, "rf": 5},
    {"name": "Buspirone 15 mg tablet", "rxnorm": "905168", "generic": "buspirone",
     "sig": "Take 1 tablet by mouth twice daily", "dose": "15", "unit": "mg", "qty": 60, "rf": 5},
    {"name": "Venlafaxine XR 150 mg capsule", "rxnorm": "311001", "generic": "venlafaxine",
     "sig": "Take 1 capsule by mouth once daily with food", "dose": "150", "unit": "mg", "qty": 30, "rf": 5},
    {"name": "Lithium carbonate 300 mg capsule", "rxnorm": "310888", "generic": "lithium",
     "sig": "Take 2 capsules by mouth three times daily — monitor levels", "dose": "300", "unit": "mg", "qty": 180, "rf": 5},
    {"name": "Quetiapine 100 mg tablet", "rxnorm": "203138", "generic": "quetiapine",
     "sig": "Take 1 tablet by mouth once daily at bedtime", "dose": "100", "unit": "mg", "qty": 30, "rf": 5},
    {"name": "Risperidone 2 mg tablet", "rxnorm": "213310", "generic": "risperidone",
     "sig": "Take 1 tablet by mouth twice daily", "dose": "2", "unit": "mg", "qty": 60, "rf": 5},
    {"name": "Aripiprazole 15 mg tablet", "rxnorm": "352364", "generic": "aripiprazole",
     "sig": "Take 1 tablet by mouth once daily", "dose": "15", "unit": "mg", "qty": 30, "rf": 5},
    {"name": "Lamotrigine 100 mg tablet", "rxnorm": "835564", "generic": "lamotrigine",
     "sig": "Take 1 tablet by mouth twice daily", "dose": "100", "unit": "mg", "qty": 60, "rf": 5},
    {"name": "Valproic acid 500 mg DR tablet", "rxnorm": "310327", "generic": "valproate",
     "sig": "Take 1 tablet by mouth twice daily with food", "dose": "500", "unit": "mg", "qty": 60, "rf": 5},
    # ADHD
    {"name": "Adderall XR 30 mg capsule", "rxnorm": "577957", "generic": "amphetamine salts",
     "sig": "Take 1 capsule by mouth every morning", "dose": "30", "unit": "mg", "qty": 30, "rf": 1},
    {"name": "Methylphenidate ER 36 mg tablet", "rxnorm": "311004", "generic": "methylphenidate",
     "sig": "Take 1 tablet by mouth every morning", "dose": "36", "unit": "mg", "qty": 30, "rf": 1},
    {"name": "Strattera 80 mg capsule", "rxnorm": "615394", "generic": "atomoxetine",
     "sig": "Take 1 capsule by mouth once daily in the morning", "dose": "80", "unit": "mg", "qty": 30, "rf": 5},
    # Thyroid
    {"name": "Levothyroxine 100 mcg tablet", "rxnorm": "966247", "generic": "levothyroxine",
     "sig": "Take 1 tablet by mouth once daily on an empty stomach 30–60 minutes before breakfast", "dose": "100", "unit": "mcg", "qty": 30, "rf": 11},
    {"name": "Methimazole 10 mg tablet", "rxnorm": "313402", "generic": "methimazole",
     "sig": "Take 1 tablet by mouth three times daily", "dose": "10", "unit": "mg", "qty": 90, "rf": 5},
    # Musculoskeletal / Pain
    {"name": "Naproxen 500 mg tablet", "rxnorm": "849574", "generic": "naproxen",
     "sig": "Take 1 tablet by mouth twice daily with food", "dose": "500", "unit": "mg", "qty": 60, "rf": 5},
    {"name": "Ibuprofen 800 mg tablet", "rxnorm": "310965", "generic": "ibuprofen",
     "sig": "Take 1 tablet by mouth three times daily with food", "dose": "800", "unit": "mg", "qty": 90, "rf": 3},
    {"name": "Meloxicam 15 mg tablet", "rxnorm": "311038", "generic": "meloxicam",
     "sig": "Take 1 tablet by mouth once daily with food", "dose": "15", "unit": "mg", "qty": 30, "rf": 5},
    {"name": "Celecoxib 200 mg capsule", "rxnorm": "309309", "generic": "celecoxib",
     "sig": "Take 1 capsule by mouth once daily with food", "dose": "200", "unit": "mg", "qty": 30, "rf": 5},
    {"name": "Tramadol 50 mg tablet", "rxnorm": "835603", "generic": "tramadol",
     "sig": "Take 1 to 2 tablets by mouth every 6 hours as needed for moderate pain", "dose": "50", "unit": "mg", "qty": 60, "rf": 0},
    {"name": "Cyclobenzaprine 10 mg tablet", "rxnorm": "311989", "generic": "cyclobenzaprine",
     "sig": "Take 1 tablet by mouth three times daily as needed for muscle spasm", "dose": "10", "unit": "mg", "qty": 30, "rf": 0},
    {"name": "Gabapentin 600 mg tablet", "rxnorm": "476149", "generic": "gabapentin",
     "sig": "Take 1 tablet by mouth three times daily", "dose": "600", "unit": "mg", "qty": 90, "rf": 5},
    {"name": "Pregabalin 75 mg capsule", "rxnorm": "187832", "generic": "pregabalin",
     "sig": "Take 1 capsule by mouth twice daily", "dose": "75", "unit": "mg", "qty": 60, "rf": 5},
    {"name": "Duloxetine 60 mg capsule (pain)", "rxnorm": "596928", "generic": "duloxetine",
     "sig": "Take 1 capsule by mouth once daily for chronic pain", "dose": "60", "unit": "mg", "qty": 30, "rf": 5},
    # Opioids
    {"name": "Hydrocodone-acetaminophen 5-325 mg tablet", "rxnorm": "857005", "generic": "hydrocodone/APAP",
     "sig": "Take 1 to 2 tablets by mouth every 4–6 hours as needed for severe pain — do not exceed 8 tablets daily", "dose": "5/325", "unit": "mg", "qty": 30, "rf": 0},
    {"name": "Oxycodone 10 mg ER tablet", "rxnorm": "1049502", "generic": "oxycodone",
     "sig": "Take 1 tablet by mouth every 12 hours for chronic pain — do not crush or chew", "dose": "10", "unit": "mg", "qty": 60, "rf": 0},
    {"name": "Morphine sulfate ER 30 mg tablet", "rxnorm": "897641", "generic": "morphine ER",
     "sig": "Take 1 tablet by mouth every 8–12 hours for chronic pain", "dose": "30", "unit": "mg", "qty": 60, "rf": 0},
    {"name": "Buprenorphine/naloxone 8/2 mg sublingual film", "rxnorm": "1432969", "generic": "buprenorphine/naloxone",
     "sig": "Place 1 film under tongue once daily — do not swallow", "dose": "8/2", "unit": "mg", "qty": 30, "rf": 1},
    # Neuro / Seizure
    {"name": "Levetiracetam 1000 mg tablet", "rxnorm": "614468", "generic": "levetiracetam",
     "sig": "Take 1 tablet by mouth twice daily", "dose": "1000", "unit": "mg", "qty": 60, "rf": 5},
    {"name": "Phenytoin 100 mg capsule ER", "rxnorm": "727316", "generic": "phenytoin",
     "sig": "Take 1 capsule by mouth three times daily — monitor levels", "dose": "100", "unit": "mg", "qty": 90, "rf": 5},
    {"name": "Topiramate 100 mg tablet", "rxnorm": "312882", "generic": "topiramate",
     "sig": "Take 1 tablet by mouth twice daily", "dose": "100", "unit": "mg", "qty": 60, "rf": 5},
    {"name": "Donepezil 10 mg tablet", "rxnorm": "309577", "generic": "donepezil",
     "sig": "Take 1 tablet by mouth once daily at bedtime", "dose": "10", "unit": "mg", "qty": 30, "rf": 5},
    {"name": "Memantine 10 mg tablet", "rxnorm": "334857", "generic": "memantine",
     "sig": "Take 1 tablet by mouth twice daily", "dose": "10", "unit": "mg", "qty": 60, "rf": 5},
    {"name": "Carbidopa-levodopa 25-100 mg tablet", "rxnorm": "308460", "generic": "carbidopa/levodopa",
     "sig": "Take 1 tablet by mouth three times daily — not within 1 hour of meals", "dose": "25/100", "unit": "mg", "qty": 90, "rf": 5},
    # Rheumatology / Immune
    {"name": "Hydroxychloroquine 200 mg tablet", "rxnorm": "5521", "generic": "hydroxychloroquine",
     "sig": "Take 1 tablet by mouth twice daily with meals", "dose": "200", "unit": "mg", "qty": 60, "rf": 11},
    {"name": "Methotrexate 2.5 mg tablet", "rxnorm": "314877", "generic": "methotrexate",
     "sig": "Take 6 tablets by mouth once weekly on the same day each week — take folic acid daily", "dose": "2.5", "unit": "mg", "qty": 24, "rf": 3},
    {"name": "Prednisone 5 mg tablet", "rxnorm": "312617", "generic": "prednisone",
     "sig": "Take 2 tablets by mouth once daily — taper as directed", "dose": "5", "unit": "mg", "qty": 60, "rf": 3},
    {"name": "Colchicine 0.6 mg tablet", "rxnorm": "141927", "generic": "colchicine",
     "sig": "Take 1 tablet by mouth twice daily for gout prophylaxis", "dose": "0.6", "unit": "mg", "qty": 60, "rf": 5},
    {"name": "Allopurinol 300 mg tablet", "rxnorm": "197327", "generic": "allopurinol",
     "sig": "Take 1 tablet by mouth once daily", "dose": "300", "unit": "mg", "qty": 30, "rf": 11},
    # Antibiotics (short course)
    {"name": "Azithromycin 250 mg tablet (Z-pack)", "rxnorm": "308460", "generic": "azithromycin",
     "sig": "Take 2 tablets day 1, then 1 tablet daily for 4 more days", "dose": "250", "unit": "mg", "qty": 6, "rf": 0},
    {"name": "Amoxicillin 500 mg capsule", "rxnorm": "723", "generic": "amoxicillin",
     "sig": "Take 1 capsule by mouth three times daily for 10 days", "dose": "500", "unit": "mg", "qty": 30, "rf": 0},
    {"name": "Doxycycline hyclate 100 mg capsule", "rxnorm": "1648767", "generic": "doxycycline",
     "sig": "Take 1 capsule by mouth twice daily with a full glass of water", "dose": "100", "unit": "mg", "qty": 20, "rf": 0},
    {"name": "Trimethoprim-sulfamethoxazole DS tablet", "rxnorm": "358334", "generic": "TMP-SMX",
     "sig": "Take 1 tablet by mouth twice daily for 7 days", "dose": "160/800", "unit": "mg", "qty": 14, "rf": 0},
    {"name": "Ciprofloxacin 500 mg tablet", "rxnorm": "309054", "generic": "ciprofloxacin",
     "sig": "Take 1 tablet by mouth twice daily for 7 days", "dose": "500", "unit": "mg", "qty": 14, "rf": 0},
    # HIV / Hepatitis
    {"name": "Biktarvy (bictegravir-TAF-FTC) 50-25-200 mg tablet", "rxnorm": "1999675", "generic": "bictegravir/TAF/FTC",
     "sig": "Take 1 tablet by mouth once daily with or without food", "dose": "50/25/200", "unit": "mg", "qty": 30, "rf": 11},
    {"name": "Ledipasvir-sofosbuvir 90-400 mg tablet", "rxnorm": "1721535", "generic": "ledipasvir/sofosbuvir",
     "sig": "Take 1 tablet by mouth once daily for 12 weeks", "dose": "90/400", "unit": "mg", "qty": 84, "rf": 0},
    # Oncology
    {"name": "Tamoxifen 20 mg tablet", "rxnorm": "41493", "generic": "tamoxifen",
     "sig": "Take 1 tablet by mouth once daily", "dose": "20", "unit": "mg", "qty": 30, "rf": 11},
    {"name": "Anastrozole 1 mg tablet", "rxnorm": "258494", "generic": "anastrozole",
     "sig": "Take 1 tablet by mouth once daily", "dose": "1", "unit": "mg", "qty": 30, "rf": 11},
    {"name": "Ibrance 125 mg capsule", "rxnorm": "1726351", "generic": "palbociclib",
     "sig": "Take 1 capsule by mouth once daily for 21 days, then 7 days off; repeat cycle", "dose": "125", "unit": "mg", "qty": 21, "rf": 3},
    # Renal / Dialysis
    {"name": "Sevelamer carbonate 800 mg tablet", "rxnorm": "722086", "generic": "sevelamer",
     "sig": "Take 2 tablets by mouth three times daily with meals", "dose": "800", "unit": "mg", "qty": 180, "rf": 11},
    {"name": "Epoetin alfa 10000 units/mL injection", "rxnorm": "1299745", "generic": "epoetin alfa",
     "sig": "Inject 10,000 units subcutaneously three times per week — per nephrology protocol", "dose": "10000", "unit": "units", "qty": 12, "rf": 3},
    # Misc / OTC / Supplements
    {"name": "Vitamin D3 2000 IU capsule", "rxnorm": "2200\x35", "generic": "cholecalciferol",
     "sig": "Take 1 capsule by mouth once daily", "dose": "2000", "unit": "IU", "qty": 90, "rf": 3},
    {"name": "Vitamin B12 1000 mcg tablet", "rxnorm": "1049637", "generic": "cyanocobalamin",
     "sig": "Take 1 tablet by mouth once daily", "dose": "1000", "unit": "mcg", "qty": 30, "rf": 11},
    {"name": "Folic acid 1 mg tablet", "rxnorm": "353135", "generic": "folic acid",
     "sig": "Take 1 tablet by mouth once daily", "dose": "1", "unit": "mg", "qty": 30, "rf": 11},
    {"name": "Ferrous sulfate 325 mg tablet", "rxnorm": "310325", "generic": "ferrous sulfate",
     "sig": "Take 1 tablet by mouth twice daily on an empty stomach if tolerated", "dose": "325", "unit": "mg", "qty": 60, "rf": 5},
    {"name": "Calcium carbonate 600 mg + Vitamin D 400 IU tablet", "rxnorm": "318076", "generic": "calcium/vitamin D",
     "sig": "Take 1 tablet by mouth twice daily with meals", "dose": "600", "unit": "mg", "qty": 60, "rf": 11},
    {"name": "Acetaminophen 500 mg tablet", "rxnorm": "198440", "generic": "acetaminophen",
     "sig": "Take 1–2 tablets by mouth every 6 hours as needed for pain — do not exceed 3000 mg daily", "dose": "500", "unit": "mg", "qty": 100, "rf": 3},
    {"name": "Zofran ODT 4 mg tablet", "rxnorm": "312087", "generic": "ondansetron",
     "sig": "Dissolve 1 tablet under tongue every 6 hours as needed for nausea", "dose": "4", "unit": "mg", "qty": 12, "rf": 2},
    # Sleep / Sedatives
    {"name": "Trazodone 100 mg tablet", "rxnorm": "315234", "generic": "trazodone",
     "sig": "Take 1 tablet by mouth 30 minutes before bedtime as needed for sleep", "dose": "100", "unit": "mg", "qty": 30, "rf": 3},
    {"name": "Zolpidem 10 mg tablet", "rxnorm": "836637", "generic": "zolpidem",
     "sig": "Take 1 tablet by mouth immediately before bedtime — max 7–10 days", "dose": "10", "unit": "mg", "qty": 30, "rf": 0},
    {"name": "Melatonin 5 mg tablet", "rxnorm": "UNK", "generic": "melatonin",
     "sig": "Take 1 tablet by mouth 30–60 minutes before bedtime", "dose": "5", "unit": "mg", "qty": 60, "rf": 3},
    # Allergy / ENT
    {"name": "Cetirizine 10 mg tablet", "rxnorm": "1049635", "generic": "cetirizine",
     "sig": "Take 1 tablet by mouth once daily as needed for allergy symptoms", "dose": "10", "unit": "mg", "qty": 30, "rf": 3},
    {"name": "Loratadine 10 mg tablet", "rxnorm": "311372", "generic": "loratadine",
     "sig": "Take 1 tablet by mouth once daily", "dose": "10", "unit": "mg", "qty": 30, "rf": 3},
    {"name": "Fluticasone nasal spray 50 mcg/spray", "rxnorm": "1797831", "generic": "fluticasone nasal",
     "sig": "Spray 2 sprays in each nostril once daily", "dose": "50", "unit": "mcg", "qty": 1, "rf": 3},
    # Dermatology
    {"name": "Triamcinolone 0.1% cream 15g", "rxnorm": "313997", "generic": "triamcinolone",
     "sig": "Apply a thin layer to affected area twice daily — avoid face", "dose": "0.1", "unit": "%", "qty": 1, "rf": 2},
    {"name": "Clobetasol 0.05% ointment 30g", "rxnorm": "309044", "generic": "clobetasol",
     "sig": "Apply a thin layer to affected area twice daily for no more than 2 consecutive weeks", "dose": "0.05", "unit": "%", "qty": 1, "rf": 1},
    # Pediatric
    {"name": "Amoxicillin 250 mg/5 mL oral suspension", "rxnorm": "392151", "generic": "amoxicillin suspension",
     "sig": "Give 10 mL (500 mg) by mouth twice daily for 10 days; refrigerate", "dose": "250", "unit": "mg/5mL", "qty": 1, "rf": 0},
    {"name": "Ibuprofen 100 mg/5 mL oral suspension", "rxnorm": "198442", "generic": "ibuprofen suspension",
     "sig": "Give per weight-based dosing chart every 6–8 hours as needed for fever or pain", "dose": "100", "unit": "mg/5mL", "qty": 1, "rf": 0},
    # Ophthalmology
    {"name": "Latanoprost 0.005% ophthalmic solution", "rxnorm": "310298", "generic": "latanoprost",
     "sig": "Instill 1 drop in affected eye(s) once daily at bedtime", "dose": "0.005", "unit": "%", "qty": 1, "rf": 5},
    {"name": "Timolol 0.5% ophthalmic solution", "rxnorm": "310430", "generic": "timolol ophthalmic",
     "sig": "Instill 1 drop in affected eye(s) twice daily", "dose": "0.5", "unit": "%", "qty": 1, "rf": 5},
]

# ---------------------------------------------------------------------------
# LABORATORY TESTS — loinc, name, units, (normal_low, normal_high), critical_low, critical_high
# ---------------------------------------------------------------------------
LAB_TESTS = {
    # ---- CBC ----
    "WBC": {"loinc": "6690-2", "name": "White Blood Cell Count", "unit": "10*3/uL",
             "normal": (4.5, 11.0), "critical_low": 2.0, "critical_high": 30.0,
             "interp_low": "L", "interp_high": "H", "panel": "CBC"},
    "RBC": {"loinc": "789-8", "name": "Red Blood Cell Count", "unit": "10*6/uL",
             "normal": (4.2, 5.4), "critical_low": 2.0, "critical_high": 7.0,
             "interp_low": "L", "interp_high": "H", "panel": "CBC"},
    "Hemoglobin": {"loinc": "718-7", "name": "Hemoglobin", "unit": "g/dL",
                    "normal": (12.0, 17.5), "critical_low": 7.0, "critical_high": 20.0,
                    "interp_low": "L", "interp_high": "H", "panel": "CBC"},
    "Hematocrit": {"loinc": "4544-3", "name": "Hematocrit", "unit": "%",
                    "normal": (36.0, 52.0), "critical_low": 20.0, "critical_high": 60.0,
                    "interp_low": "L", "interp_high": "H", "panel": "CBC"},
    "MCV": {"loinc": "787-2", "name": "Mean Corpuscular Volume", "unit": "fL",
             "normal": (80.0, 100.0), "critical_low": 60.0, "critical_high": 120.0,
             "interp_low": "L", "interp_high": "H", "panel": "CBC"},
    "Platelets": {"loinc": "777-3", "name": "Platelet Count", "unit": "10*3/uL",
                   "normal": (150.0, 400.0), "critical_low": 50.0, "critical_high": 1000.0,
                   "interp_low": "L", "interp_high": "H", "panel": "CBC"},
    "Neutrophils_%": {"loinc": "770-8", "name": "Neutrophils %", "unit": "%",
                       "normal": (50.0, 70.0), "critical_low": 10.0, "critical_high": 95.0,
                       "interp_low": "L", "interp_high": "H", "panel": "CBC Differential"},
    "Lymphocytes_%": {"loinc": "736-9", "name": "Lymphocytes %", "unit": "%",
                       "normal": (20.0, 40.0), "critical_low": 5.0, "critical_high": 60.0,
                       "interp_low": "L", "interp_high": "H", "panel": "CBC Differential"},
    # ---- BMP / CMP ----
    "Sodium": {"loinc": "2951-2", "name": "Sodium", "unit": "mEq/L",
                "normal": (136.0, 145.0), "critical_low": 120.0, "critical_high": 160.0,
                "interp_low": "L", "interp_high": "H", "panel": "BMP"},
    "Potassium": {"loinc": "2823-3", "name": "Potassium", "unit": "mEq/L",
                   "normal": (3.5, 5.0), "critical_low": 2.5, "critical_high": 6.5,
                   "interp_low": "L", "interp_high": "H", "panel": "BMP"},
    "Chloride": {"loinc": "2075-0", "name": "Chloride", "unit": "mEq/L",
                  "normal": (98.0, 107.0), "critical_low": 80.0, "critical_high": 115.0,
                  "interp_low": "L", "interp_high": "H", "panel": "BMP"},
    "CO2": {"loinc": "2028-9", "name": "Carbon Dioxide (Bicarbonate)", "unit": "mEq/L",
             "normal": (22.0, 29.0), "critical_low": 10.0, "critical_high": 40.0,
             "interp_low": "L", "interp_high": "H", "panel": "BMP"},
    "BUN": {"loinc": "3094-0", "name": "BUN (Blood Urea Nitrogen)", "unit": "mg/dL",
             "normal": (7.0, 20.0), "critical_low": None, "critical_high": 100.0,
             "interp_low": "L", "interp_high": "H", "panel": "BMP"},
    "Creatinine": {"loinc": "2160-0", "name": "Creatinine, serum", "unit": "mg/dL",
                    "normal": (0.6, 1.2), "critical_low": None, "critical_high": 10.0,
                    "interp_low": "L", "interp_high": "H", "panel": "BMP"},
    "Glucose": {"loinc": "2345-7", "name": "Glucose, serum", "unit": "mg/dL",
                 "normal": (70.0, 100.0), "critical_low": 40.0, "critical_high": 500.0,
                 "interp_low": "L", "interp_high": "H", "panel": "BMP"},
    "eGFR": {"loinc": "98979-8", "name": "eGFR (CKD-EPI)", "unit": "mL/min/1.73m2",
              "normal": (60.0, 120.0), "critical_low": 15.0, "critical_high": None,
              "interp_low": "L", "interp_high": "H", "panel": "BMP"},
    "Calcium": {"loinc": "17861-6", "name": "Calcium, serum", "unit": "mg/dL",
                 "normal": (8.5, 10.5), "critical_low": 6.5, "critical_high": 13.0,
                 "interp_low": "L", "interp_high": "H", "panel": "CMP"},
    "AST": {"loinc": "1920-8", "name": "AST (Aspartate aminotransferase)", "unit": "U/L",
             "normal": (10.0, 40.0), "critical_low": None, "critical_high": 500.0,
             "interp_low": "L", "interp_high": "H", "panel": "LFT"},
    "ALT": {"loinc": "1742-6", "name": "ALT (Alanine aminotransferase)", "unit": "U/L",
             "normal": (7.0, 56.0), "critical_low": None, "critical_high": 500.0,
             "interp_low": "L", "interp_high": "H", "panel": "LFT"},
    "ALP": {"loinc": "6768-6", "name": "Alkaline Phosphatase", "unit": "U/L",
             "normal": (44.0, 147.0), "critical_low": None, "critical_high": 800.0,
             "interp_low": "L", "interp_high": "H", "panel": "LFT"},
    "Total Bilirubin": {"loinc": "1975-2", "name": "Total Bilirubin", "unit": "mg/dL",
                         "normal": (0.2, 1.2), "critical_low": None, "critical_high": 15.0,
                         "interp_low": "L", "interp_high": "H", "panel": "LFT"},
    "Albumin": {"loinc": "1751-7", "name": "Albumin, serum", "unit": "g/dL",
                 "normal": (3.5, 5.0), "critical_low": 1.5, "critical_high": None,
                 "interp_low": "L", "interp_high": "H", "panel": "CMP"},
    "Total Protein": {"loinc": "2885-2", "name": "Total Protein", "unit": "g/dL",
                       "normal": (6.3, 8.2), "critical_low": None, "critical_high": None,
                       "interp_low": "L", "interp_high": "H", "panel": "CMP"},
    # ---- Lipid Panel ----
    "Total Cholesterol": {"loinc": "2093-3", "name": "Total Cholesterol", "unit": "mg/dL",
                           "normal": (0.0, 200.0), "critical_low": None, "critical_high": 300.0,
                           "interp_low": "N", "interp_high": "H", "panel": "Lipid Panel"},
    "LDL": {"loinc": "2089-1", "name": "LDL Cholesterol", "unit": "mg/dL",
             "normal": (0.0, 100.0), "critical_low": None, "critical_high": 190.0,
             "interp_low": "N", "interp_high": "H", "panel": "Lipid Panel"},
    "HDL": {"loinc": "2085-9", "name": "HDL Cholesterol", "unit": "mg/dL",
             "normal": (40.0, 200.0), "critical_low": 20.0, "critical_high": None,
             "interp_low": "L", "interp_high": "N", "panel": "Lipid Panel"},
    "Triglycerides": {"loinc": "2571-8", "name": "Triglycerides", "unit": "mg/dL",
                       "normal": (0.0, 150.0), "critical_low": None, "critical_high": 500.0,
                       "interp_low": "N", "interp_high": "H", "panel": "Lipid Panel"},
    # ---- Endocrine / DM ----
    "HbA1c": {"loinc": "4548-4", "name": "Hemoglobin A1c", "unit": "%",
               "normal": (4.0, 5.7), "critical_low": None, "critical_high": 14.0,
               "interp_low": "N", "interp_high": "H", "panel": "Diabetes Monitoring"},
    "Fasting Glucose": {"loinc": "1558-6", "name": "Glucose, fasting", "unit": "mg/dL",
                         "normal": (70.0, 100.0), "critical_low": 40.0, "critical_high": 500.0,
                         "interp_low": "L", "interp_high": "H", "panel": "Diabetes Monitoring"},
    "C-Peptide": {"loinc": "1986-9", "name": "C-Peptide", "unit": "ng/mL",
                   "normal": (0.8, 3.1), "critical_low": None, "critical_high": None,
                   "interp_low": "L", "interp_high": "H", "panel": "Diabetes Monitoring"},
    "TSH": {"loinc": "3016-3", "name": "TSH (Thyroid Stimulating Hormone)", "unit": "mIU/L",
             "normal": (0.4, 4.0), "critical_low": 0.01, "critical_high": 20.0,
             "interp_low": "L", "interp_high": "H", "panel": "Thyroid"},
    "Free T4": {"loinc": "3024-7", "name": "Free T4 (Thyroxine)", "unit": "ng/dL",
                 "normal": (0.8, 1.8), "critical_low": None, "critical_high": None,
                 "interp_low": "L", "interp_high": "H", "panel": "Thyroid"},
    "Free T3": {"loinc": "3051-0", "name": "Free T3 (Triiodothyronine)", "unit": "pg/mL",
                 "normal": (2.3, 4.2), "critical_low": None, "critical_high": None,
                 "interp_low": "L", "interp_high": "H", "panel": "Thyroid"},
    "Cortisol AM": {"loinc": "2143-6", "name": "Cortisol, AM (8 AM)", "unit": "mcg/dL",
                     "normal": (6.0, 23.0), "critical_low": 2.0, "critical_high": None,
                     "interp_low": "L", "interp_high": "H", "panel": "Adrenal"},
    # ---- Cardiac ----
    "Troponin I": {"loinc": "10839-9", "name": "Troponin I, cardiac", "unit": "ng/mL",
                    "normal": (0.0, 0.04), "critical_low": None, "critical_high": 2.0,
                    "interp_low": "N", "interp_high": "H", "panel": "Cardiac Markers"},
    "BNP": {"loinc": "42637-9", "name": "BNP (B-type natriuretic peptide)", "unit": "pg/mL",
             "normal": (0.0, 100.0), "critical_low": None, "critical_high": 900.0,
             "interp_low": "N", "interp_high": "H", "panel": "Cardiac Markers"},
    "Pro-BNP": {"loinc": "33762-6", "name": "NT-proBNP", "unit": "pg/mL",
                 "normal": (0.0, 300.0), "critical_low": None, "critical_high": 5000.0,
                 "interp_low": "N", "interp_high": "H", "panel": "Cardiac Markers"},
    "CRP": {"loinc": "1988-5", "name": "C-Reactive Protein", "unit": "mg/L",
             "normal": (0.0, 10.0), "critical_low": None, "critical_high": 200.0,
             "interp_low": "N", "interp_high": "H", "panel": "Inflammatory Markers"},
    "ESR": {"loinc": "4537-7", "name": "Erythrocyte Sedimentation Rate", "unit": "mm/hr",
             "normal": (0.0, 20.0), "critical_low": None, "critical_high": 120.0,
             "interp_low": "N", "interp_high": "H", "panel": "Inflammatory Markers"},
    "D-Dimer": {"loinc": "48066-5", "name": "D-Dimer", "unit": "mcg/mL FEU",
                 "normal": (0.0, 0.5), "critical_low": None, "critical_high": 4.0,
                 "interp_low": "N", "interp_high": "H", "panel": "Coagulation"},
    "PT/INR": {"loinc": "34714-6", "name": "INR (Prothrombin time ratio)", "unit": "INR",
                "normal": (0.9, 1.1), "critical_low": None, "critical_high": 5.0,
                "interp_low": "N", "interp_high": "H", "panel": "Coagulation"},
    # ---- Renal / Urine ----
    "Urine Microalbumin": {"loinc": "14957-5", "name": "Urine Microalbumin", "unit": "mg/g creatinine",
                            "normal": (0.0, 30.0), "critical_low": None, "critical_high": 3000.0,
                            "interp_low": "N", "interp_high": "H", "panel": "Urine Studies"},
    "Urine Creatinine": {"loinc": "2161-8", "name": "Urine Creatinine", "unit": "mg/dL",
                          "normal": (20.0, 300.0), "critical_low": None, "critical_high": None,
                          "interp_low": "L", "interp_high": "H", "panel": "Urine Studies"},
    "Uric Acid": {"loinc": "3084-1", "name": "Uric Acid, serum", "unit": "mg/dL",
                   "normal": (3.5, 7.2), "critical_low": None, "critical_high": 13.0,
                   "interp_low": "L", "interp_high": "H", "panel": "Metabolic"},
    "Phosphorus": {"loinc": "2777-1", "name": "Phosphorus, serum", "unit": "mg/dL",
                    "normal": (2.5, 4.5), "critical_low": 1.0, "critical_high": 8.0,
                    "interp_low": "L", "interp_high": "H", "panel": "CMP"},
    "Magnesium": {"loinc": "2601-3", "name": "Magnesium, serum", "unit": "mg/dL",
                   "normal": (1.7, 2.2), "critical_low": 1.0, "critical_high": 4.0,
                   "interp_low": "L", "interp_high": "H", "panel": "Electrolytes"},
    # ---- Hematology ----
    "Ferritin": {"loinc": "2276-4", "name": "Ferritin", "unit": "ng/mL",
                  "normal": (12.0, 300.0), "critical_low": 5.0, "critical_high": 2000.0,
                  "interp_low": "L", "interp_high": "H", "panel": "Iron Studies"},
    "Iron, serum": {"loinc": "2498-4", "name": "Iron, serum", "unit": "mcg/dL",
                     "normal": (60.0, 170.0), "critical_low": 20.0, "critical_high": None,
                     "interp_low": "L", "interp_high": "H", "panel": "Iron Studies"},
    "TIBC": {"loinc": "2501-5", "name": "Total Iron Binding Capacity (TIBC)", "unit": "mcg/dL",
              "normal": (250.0, 370.0), "critical_low": None, "critical_high": None,
              "interp_low": "L", "interp_high": "H", "panel": "Iron Studies"},
    "Vitamin B12": {"loinc": "2132-9", "name": "Vitamin B12 (cobalamin)", "unit": "pg/mL",
                     "normal": (200.0, 900.0), "critical_low": 100.0, "critical_high": None,
                     "interp_low": "L", "interp_high": "H", "panel": "Vitamins"},
    "Folate": {"loinc": "2284-8", "name": "Folate (serum)", "unit": "ng/mL",
                "normal": (3.1, 20.0), "critical_low": 2.0, "critical_high": None,
                "interp_low": "L", "interp_high": "H", "panel": "Vitamins"},
    "Vitamin D 25-OH": {"loinc": "1989-3", "name": "Vitamin D, 25-Hydroxyvitamin D", "unit": "ng/mL",
                         "normal": (30.0, 80.0), "critical_low": 10.0, "critical_high": 150.0,
                         "interp_low": "L", "interp_high": "H", "panel": "Vitamins"},
    # ---- Rheumatology ----
    "ANA": {"loinc": "5048-0", "name": "Antinuclear Antibody (ANA)", "unit": "titer",
             "normal": (0.0, 1.0), "critical_low": None, "critical_high": None,
             "interp_low": "N", "interp_high": "H", "panel": "Autoimmune"},
    "RF": {"loinc": "11572-5", "name": "Rheumatoid Factor", "unit": "IU/mL",
            "normal": (0.0, 14.0), "critical_low": None, "critical_high": None,
            "interp_low": "N", "interp_high": "H", "panel": "Autoimmune"},
    "Anti-CCP": {"loinc": "33902-8", "name": "Anti-CCP Antibody", "unit": "U/mL",
                  "normal": (0.0, 20.0), "critical_low": None, "critical_high": None,
                  "interp_low": "N", "interp_high": "H", "panel": "Autoimmune"},
    # ---- Infectious Disease / STI ----
    "HIV Ag/Ab Combo": {"loinc": "75622-1", "name": "HIV-1/2 Antigen/Antibody Combination", "unit": "result",
                          "normal": (0.0, 1.0), "critical_low": None, "critical_high": None,
                          "interp_low": "N", "interp_high": "H", "panel": "Infectious Disease"},
    "Hep B Surface Ag": {"loinc": "5195-9", "name": "Hepatitis B Surface Antigen", "unit": "result",
                           "normal": (0.0, 1.0), "critical_low": None, "critical_high": None,
                           "interp_low": "N", "interp_high": "H", "panel": "Hepatitis"},
    "Hep C Ab": {"loinc": "16128-1", "name": "Hepatitis C Virus Antibody", "unit": "result",
                  "normal": (0.0, 1.0), "critical_low": None, "critical_high": None,
                  "interp_low": "N", "interp_high": "H", "panel": "Hepatitis"},
    "RPR": {"loinc": "20508-0", "name": "RPR (Syphilis screen)", "unit": "result",
             "normal": (0.0, 1.0), "critical_low": None, "critical_high": None,
             "interp_low": "N", "interp_high": "H", "panel": "STI Panel"},
    "GC/CT NAAT": {"loinc": "21613-5", "name": "GC/Chlamydia NAAT", "unit": "result",
                    "normal": (0.0, 1.0), "critical_low": None, "critical_high": None,
                    "interp_low": "N", "interp_high": "H", "panel": "STI Panel"},
    # ---- Oncology Markers ----
    "PSA": {"loinc": "2857-1", "name": "PSA (Prostate Specific Antigen)", "unit": "ng/mL",
             "normal": (0.0, 4.0), "critical_low": None, "critical_high": 20.0,
             "interp_low": "N", "interp_high": "H", "panel": "Tumor Markers"},
    "CA 125": {"loinc": "10334-1", "name": "CA 125 (Cancer Antigen 125)", "unit": "U/mL",
                "normal": (0.0, 35.0), "critical_low": None, "critical_high": 500.0,
                "interp_low": "N", "interp_high": "H", "panel": "Tumor Markers"},
    "CEA": {"loinc": "2857-1", "name": "CEA (Carcinoembryonic Antigen)", "unit": "ng/mL",
             "normal": (0.0, 3.0), "critical_low": None, "critical_high": 20.0,
             "interp_low": "N", "interp_high": "H", "panel": "Tumor Markers"},
    "AFP": {"loinc": "1834-1", "name": "Alpha-Fetoprotein (AFP)", "unit": "ng/mL",
             "normal": (0.0, 10.0), "critical_low": None, "critical_high": 400.0,
             "interp_low": "N", "interp_high": "H", "panel": "Tumor Markers"},
    # ---- Therapeutic Drug Levels ----
    "Digoxin level": {"loinc": "14933-6", "name": "Digoxin, serum level", "unit": "ng/mL",
                       "normal": (0.5, 2.0), "critical_low": None, "critical_high": 3.0,
                       "interp_low": "L", "interp_high": "H", "panel": "Drug Levels"},
    "Lithium level": {"loinc": "6922-9", "name": "Lithium, serum level", "unit": "mEq/L",
                       "normal": (0.6, 1.2), "critical_low": None, "critical_high": 2.0,
                       "interp_low": "L", "interp_high": "H", "panel": "Drug Levels"},
    "Phenytoin level": {"loinc": "3968-5", "name": "Phenytoin, serum level", "unit": "mcg/mL",
                         "normal": (10.0, 20.0), "critical_low": 5.0, "critical_high": 30.0,
                         "interp_low": "L", "interp_high": "H", "panel": "Drug Levels"},
    "Valproic acid level": {"loinc": "14933-6", "name": "Valproic Acid, serum level", "unit": "mcg/mL",
                              "normal": (50.0, 100.0), "critical_low": 20.0, "critical_high": 150.0,
                              "interp_low": "L", "interp_high": "H", "panel": "Drug Levels"},
    "Vancomycin trough": {"loinc": "20578-3", "name": "Vancomycin trough level", "unit": "mcg/mL",
                           "normal": (10.0, 20.0), "critical_low": 5.0, "critical_high": 40.0,
                           "interp_low": "L", "interp_high": "H", "panel": "Drug Levels"},
    # ---- Urinalysis ----
    "UA pH": {"loinc": "5764-3", "name": "Urine pH", "unit": "pH",
               "normal": (5.0, 8.0), "critical_low": None, "critical_high": None,
               "interp_low": "L", "interp_high": "H", "panel": "Urinalysis"},
    "UA Protein": {"loinc": "20454-5", "name": "Urine Protein", "unit": "mg/dL",
                    "normal": (0.0, 14.0), "critical_low": None, "critical_high": None,
                    "interp_low": "N", "interp_high": "H", "panel": "Urinalysis"},
    "UA Glucose": {"loinc": "25428-4", "name": "Urine Glucose", "unit": "mg/dL",
                    "normal": (0.0, 0.0), "critical_low": None, "critical_high": None,
                    "interp_low": "N", "interp_high": "H", "panel": "Urinalysis"},
    # ---- Less common but important ----
    "Procalcitonin": {"loinc": "75241-0", "name": "Procalcitonin", "unit": "ng/mL",
                       "normal": (0.0, 0.15), "critical_low": None, "critical_high": 10.0,
                       "interp_low": "N", "interp_high": "H", "panel": "Sepsis Markers"},
    "Lactate": {"loinc": "2519-7", "name": "Lactate, plasma", "unit": "mmol/L",
                 "normal": (0.5, 2.0), "critical_low": None, "critical_high": 4.0,
                 "interp_low": "N", "interp_high": "H", "panel": "Sepsis Markers"},
    "Ammonia": {"loinc": "1622-0", "name": "Ammonia (plasma)", "unit": "mcmol/L",
                 "normal": (16.0, 60.0), "critical_low": None, "critical_high": 150.0,
                 "interp_low": "N", "interp_high": "H", "panel": "Hepatic"},
    "DHEA-S": {"loinc": "2191-5", "name": "DHEA-Sulfate", "unit": "mcg/dL",
                "normal": (65.0, 380.0), "critical_low": None, "critical_high": None,
                "interp_low": "L", "interp_high": "H", "panel": "Adrenal"},
    "Testosterone Total": {"loinc": "2986-8", "name": "Testosterone, total", "unit": "ng/dL",
                             "normal": (300.0, 1000.0), "critical_low": 50.0, "critical_high": None,
                             "interp_low": "L", "interp_high": "H", "panel": "Sex Hormones"},
    "Estradiol": {"loinc": "2243-4", "name": "Estradiol (E2)", "unit": "pg/mL",
                   "normal": (20.0, 350.0), "critical_low": None, "critical_high": None,
                   "interp_low": "L", "interp_high": "H", "panel": "Sex Hormones"},
    "LH": {"loinc": "10501-5", "name": "Luteinizing Hormone (LH)", "unit": "mIU/mL",
            "normal": (1.0, 18.0), "critical_low": None, "critical_high": None,
            "interp_low": "L", "interp_high": "H", "panel": "Sex Hormones"},
    "FSH": {"loinc": "15067-2", "name": "Follicle Stimulating Hormone (FSH)", "unit": "mIU/mL",
             "normal": (1.0, 15.0), "critical_low": None, "critical_high": None,
             "interp_low": "L", "interp_high": "H", "panel": "Sex Hormones"},
    "hCG": {"loinc": "2110-5", "name": "hCG (Pregnancy test, quantitative)", "unit": "mIU/mL",
             "normal": (0.0, 5.0), "critical_low": None, "critical_high": None,
             "interp_low": "N", "interp_high": "H", "panel": "Pregnancy"},
    "Lyme IgG/IgM": {"loinc": "22996-2", "name": "Lyme Disease Ab (IgG/IgM)", "unit": "result",
                      "normal": (0.0, 1.0), "critical_low": None, "critical_high": None,
                      "interp_low": "N", "interp_high": "H", "panel": "Infectious Disease"},
    "SPEP": {"loinc": "2738-3", "name": "Serum Protein Electrophoresis", "unit": "result",
              "normal": (0.0, 1.0), "critical_low": None, "critical_high": None,
              "interp_low": "N", "interp_high": "H", "panel": "Hematology"},
    "HIV Viral Load": {"loinc": "20447-9", "name": "HIV-1 RNA (Viral Load)", "unit": "copies/mL",
                        "normal": (0.0, 20.0), "critical_low": None, "critical_high": 500000.0,
                        "interp_low": "N", "interp_high": "H", "panel": "Infectious Disease"},
    "CD4 Count": {"loinc": "24467-3", "name": "CD4+ T-lymphocyte count", "unit": "cells/uL",
                   "normal": (500.0, 1500.0), "critical_low": 200.0, "critical_high": None,
                   "interp_low": "L", "interp_high": "H", "panel": "Infectious Disease"},
}

# ---- Lab panel groupings for generation logic ----
LAB_PANELS = {
    "CBC": ["WBC", "RBC", "Hemoglobin", "Hematocrit", "MCV", "Platelets"],
    "CBC with Differential": ["WBC", "RBC", "Hemoglobin", "Hematocrit", "MCV", "Platelets",
                               "Neutrophils_%", "Lymphocytes_%"],
    "BMP": ["Sodium", "Potassium", "Chloride", "CO2", "BUN", "Creatinine", "Glucose", "eGFR"],
    "CMP": ["Sodium", "Potassium", "Chloride", "CO2", "BUN", "Creatinine", "Glucose", "eGFR",
            "Calcium", "Albumin", "Total Protein", "AST", "ALT", "ALP", "Total Bilirubin"],
    "Lipid Panel": ["Total Cholesterol", "LDL", "HDL", "Triglycerides"],
    "Thyroid": ["TSH", "Free T4"],
    "LFT": ["AST", "ALT", "ALP", "Total Bilirubin", "Albumin"],
    "Iron Studies": ["Ferritin", "Iron, serum", "TIBC"],
    "Inflammatory Markers": ["CRP", "ESR"],
    "Coagulation": ["PT/INR", "D-Dimer"],
    "Cardiac Markers": ["Troponin I", "BNP"],
    "Diabetes Monitoring": ["HbA1c", "Fasting Glucose"],
    "STI Panel": ["HIV Ag/Ab Combo", "RPR", "GC/CT NAAT"],
    "Hepatitis Panel": ["Hep B Surface Ag", "Hep C Ab"],
    "Tumor Markers – Male": ["PSA", "AFP", "CEA"],
    "Tumor Markers – Female": ["CA 125", "AFP", "CEA"],
    "Vitamins": ["Vitamin B12", "Folate", "Vitamin D 25-OH"],
    "Sepsis Markers": ["Procalcitonin", "Lactate", "CRP"],
    "Drug Levels – Lithium": ["Lithium level"],
    "Drug Levels – Phenytoin": ["Phenytoin level"],
    "Drug Levels – Valproate": ["Valproic acid level"],
    "Sex Hormones – Male": ["Testosterone Total", "LH", "FSH"],
    "Sex Hormones – Female": ["Estradiol", "LH", "FSH", "hCG"],
    "HIV Monitoring": ["HIV Viral Load", "CD4 Count"],
    "Autoimmune Panel": ["ANA", "RF", "Anti-CCP", "CRP", "ESR"],
}

# ---------------------------------------------------------------------------
# IMMUNIZATIONS — CVX codes
# ---------------------------------------------------------------------------
VACCINES = [
    {"name": "Influenza, seasonal injectable", "cvx": "141", "schedule": "Annual"},
    {"name": "COVID-19 mRNA (Pfizer)", "cvx": "208", "schedule": "Series"},
    {"name": "COVID-19 mRNA (Moderna)", "cvx": "207", "schedule": "Series"},
    {"name": "Tdap", "cvx": "115", "schedule": "Every 10 years"},
    {"name": "Td booster", "cvx": "113", "schedule": "Every 10 years"},
    {"name": "Pneumococcal conjugate PCV15", "cvx": "215", "schedule": "Age 65+"},
    {"name": "Pneumococcal polysaccharide PPSV23", "cvx": "33", "schedule": "Age 65+"},
    {"name": "Shingrix (RZV) dose 1", "cvx": "187", "schedule": "Age 50+"},
    {"name": "Shingrix (RZV) dose 2", "cvx": "187", "schedule": "Age 50+ (2–6 mo after dose 1)"},
    {"name": "MMR", "cvx": "03", "schedule": "Childhood"},
    {"name": "Varicella", "cvx": "21", "schedule": "Childhood"},
    {"name": "Hepatitis A, adult", "cvx": "52", "schedule": "2-dose series"},
    {"name": "Hepatitis B, adult", "cvx": "43", "schedule": "3-dose series"},
    {"name": "HPV (Gardasil 9)", "cvx": "165", "schedule": "Age 11–26"},
    {"name": "Meningococcal MenACWY", "cvx": "114", "schedule": "Adolescents / college"},
    {"name": "DTaP (pediatric)", "cvx": "20", "schedule": "Childhood series"},
    {"name": "IPV (Polio)", "cvx": "10", "schedule": "Childhood series"},
    {"name": "Hib (Haemophilus influenzae type b)", "cvx": "48", "schedule": "Infant"},
    {"name": "PCV13 (Prevnar 13, pediatric)", "cvx": "133", "schedule": "Infant series"},
    {"name": "Rotavirus (RV5)", "cvx": "116", "schedule": "Infant"},
    {"name": "RSV vaccine (Abrysvo)", "cvx": "299", "schedule": "Age 60+"},
    {"name": "Hepatitis B (Heplisav-B, 2-dose)", "cvx": "189", "schedule": "Adults 18+"},
]

# ---------------------------------------------------------------------------
# PROCEDURES — CPT codes
# ---------------------------------------------------------------------------
PROCEDURES = [
    {"name": "Office visit, established patient (99213)", "cpt": "99213"},
    {"name": "Office visit, established patient (99214)", "cpt": "99214"},
    {"name": "Annual wellness visit (99395)", "cpt": "99395"},
    {"name": "Pap smear (88141)", "cpt": "88141"},
    {"name": "Colonoscopy, diagnostic (45378)", "cpt": "45378"},
    {"name": "Colonoscopy with polypectomy (45385)", "cpt": "45385"},
    {"name": "EGD / Upper endoscopy (43239)", "cpt": "43239"},
    {"name": "Chest X-ray, 2 views (71046)", "cpt": "71046"},
    {"name": "ECG, 12-lead with interpretation (93000)", "cpt": "93000"},
    {"name": "Echocardiogram, transthoracic (93306)", "cpt": "93306"},
    {"name": "Stress test with imaging (93351)", "cpt": "93351"},
    {"name": "Spirometry (94010)", "cpt": "94010"},
    {"name": "Pulmonary function tests, complete (94060)", "cpt": "94060"},
    {"name": "Bone density (DEXA) (77080)", "cpt": "77080"},
    {"name": "Mammogram, digital (77065)", "cpt": "77065"},
    {"name": "Ultrasound, thyroid (76536)", "cpt": "76536"},
    {"name": "Ultrasound, renal (76770)", "cpt": "76770"},
    {"name": "Ultrasound, pelvic (76856)", "cpt": "76856"},
    {"name": "CT scan, abdomen/pelvis with contrast (74177)", "cpt": "74177"},
    {"name": "CT scan, chest with contrast (71250)", "cpt": "71250"},
    {"name": "MRI, brain without contrast (70553)", "cpt": "70553"},
    {"name": "MRI, lumbar spine (72148)", "cpt": "72148"},
    {"name": "EEG (95816)", "cpt": "95816"},
    {"name": "EMG / Nerve conduction study (95911)", "cpt": "95911"},
    {"name": "Knee injection (cortisone) (20610)", "cpt": "20610"},
    {"name": "Skin biopsy (11102)", "cpt": "11102"},
    {"name": "I&D, abscess (10060)", "cpt": "10060"},
    {"name": "Removal, skin lesion (11300)", "cpt": "11300"},
    {"name": "Spirometry with bronchodilator (94060)", "cpt": "94060"},
    {"name": "Glucose tolerance test (82950)", "cpt": "82950"},
    {"name": "24-hour ambulatory BP monitor (93784)", "cpt": "93784"},
    {"name": "Holter monitor 48h (93224)", "cpt": "93224"},
    {"name": "Flexible sigmoidoscopy (45330)", "cpt": "45330"},
    {"name": "Cerumen removal (69210)", "cpt": "69210"},
    {"name": "Nebulization treatment in-office (94640)", "cpt": "94640"},
    {"name": "COVID-19 rapid antigen test (87426)", "cpt": "87426"},
    {"name": "Influenza A+B rapid test (87804)", "cpt": "87804"},
    {"name": "Strep A rapid test (87880)", "cpt": "87880"},
    {"name": "Urine culture (87086)", "cpt": "87086"},
    {"name": "Wound care / dressing change (97602)", "cpt": "97602"},
]

# ---------------------------------------------------------------------------
# SOCIAL HISTORY OPTIONS
# ---------------------------------------------------------------------------
SMOKING_STATUSES = [
    ("Never smoker", "266919005"), ("Former smoker — quit > 1 year ago", "8517006"),
    ("Former smoker — quit < 1 year ago", "8517006"), ("Current daily smoker", "449868002"),
    ("Current occasional smoker", "428041000124106"), ("Passive/secondhand exposure", "77176002"),
    ("Smokeless tobacco user", "81703003"), ("Electronic cigarette/vaping user", "722498001"),
]
ALCOHOL_USE = [
    "Denies alcohol use", "Social drinker — 1 to 3 drinks per week",
    "Moderate drinker — 4 to 7 drinks per week", "Heavy drinker — > 14 drinks per week",
    "Binge drinker — 5+ drinks on occasion", "History of alcohol abuse, currently in recovery",
    "Active alcohol use disorder", "Alcohol use disorder, in remission",
]
DRUG_USE = [
    "Denies illicit drug use", "Remote marijuana use, no current use",
    "Active marijuana use (recreational)", "Active marijuana use (medicinal)",
    "History of cocaine use, currently abstinent", "Active cocaine use",
    "History of opioid misuse, now in MAT (buprenorphine)",
    "History of IV drug use, currently abstinent",
    "Denies recreational drug use; takes all medications as prescribed",
]
EXERCISE = [
    "Sedentary — less than 30 min/week", "Mildly active — 30–60 min/week light activity",
    "Moderately active — 150 min/week as recommended", "Highly active — >300 min/week",
    "Unable to exercise due to medical condition",
    "Walks 30 minutes daily", "Exercises 3–4 times per week at gym",
]
OCCUPATIONS = [
    "Retired", "Disabled — unable to work", "Office administrator", "Registered nurse",
    "Teacher", "Engineer", "Construction worker", "Truck driver", "Chef/cook",
    "Lawyer", "Accountant", "Homemaker", "Student", "Retail worker", "Warehouse worker",
    "Healthcare worker", "Police officer", "Firefighter", "Farmer", "Mechanic",
    "Social worker", "Software developer", "Electrician", "Plumber", "Real estate agent",
    "Unemployed — seeking work", "Self-employed", "Military (active duty)", "Veteran",
]

# ---------------------------------------------------------------------------
# FAMILY HISTORY
# ---------------------------------------------------------------------------
FAMILY_HISTORY_CONDITIONS = [
    "Hypertension", "Type 2 diabetes mellitus", "Coronary artery disease",
    "Heart failure", "Stroke / CVA", "Atrial fibrillation",
    "Breast cancer", "Colon cancer", "Prostate cancer", "Ovarian cancer",
    "Lung cancer", "Pancreatic cancer", "Melanoma",
    "Alzheimer dementia", "Parkinson disease",
    "COPD / Emphysema", "Asthma",
    "Osteoporosis", "Rheumatoid arthritis", "Lupus",
    "Depression", "Bipolar disorder", "Schizophrenia", "Anxiety disorder",
    "Alcohol use disorder", "Substance use disorder",
    "Hypothyroidism", "Hyperthyroidism",
    "Chronic kidney disease", "Kidney stones",
    "Glaucoma", "Macular degeneration",
    "Deep vein thrombosis / Pulmonary embolism",
    "Sickle cell disease", "Hemophilia",
    "HIV/AIDS", "Hepatitis C",
    "Autism spectrum disorder", "Down syndrome",
    "Sudden cardiac death at young age", "Aortic aneurysm",
]
FAMILY_MEMBERS = [
    "Mother", "Father", "Maternal grandmother", "Maternal grandfather",
    "Paternal grandmother", "Paternal grandfather", "Older brother", "Older sister",
    "Younger brother", "Younger sister", "Maternal uncle", "Maternal aunt",
    "Paternal uncle", "Paternal aunt",
]

# ---------------------------------------------------------------------------
# STREET / ADDRESS DATA
# ---------------------------------------------------------------------------
STREET_NAMES = [
    "Oak Street", "Maple Avenue", "Cedar Lane", "Pine Drive", "Elm Court",
    "Willow Way", "Birch Boulevard", "Spruce Circle", "Walnut Road", "Cherry Hill Drive",
    "Sunset Boulevard", "Sunrise Lane", "River Road", "Lake View Drive", "Mountain View Place",
    "Heritage Drive", "Colonial Way", "Patriot Lane", "Liberty Street", "Freedom Court",
    "Independence Boulevard", "Union Avenue", "Commerce Street", "Market Street", "Main Street",
    "Washington Drive", "Jefferson Avenue", "Lincoln Boulevard", "Madison Court", "Monroe Place",
    "Rolling Hills Lane", "Meadow Brook Drive", "Stonebridge Court", "Foxcroft Road",
    "Briarwood Lane", "Kingswood Drive", "Queensbury Way", "Ashford Place", "Harrington Court",
    "Thornberry Lane", "Millbrook Drive", "Creekside Court", "Ridgeline Road", "Valley View Lane",
    "Windmill Drive", "Waterford Way", "Stonehaven Court", "Greenfield Road", "Clearwater Lane",
]
CITIES_STATES = [
    ("Richmond", "VA", "23220"), ("Midlothian", "VA", "23114"), ("Chesterfield", "VA", "23832"),
    ("Henrico", "VA", "23294"), ("Glen Allen", "VA", "23060"), ("Mechanicsville", "VA", "23111"),
    ("Chester", "VA", "23831"), ("Colonial Heights", "VA", "23834"),
    ("Charlottesville", "VA", "22901"), ("Roanoke", "VA", "24011"),
    ("Norfolk", "VA", "23501"), ("Virginia Beach", "VA", "23451"),
    ("Newport News", "VA", "23601"), ("Hampton", "VA", "23661"),
    ("Alexandria", "VA", "22301"), ("Fredericksburg", "VA", "22401"),
    ("Arlington", "VA", "22201"), ("Sterling", "VA", "20164"),
    ("Woodbridge", "VA", "22191"), ("Manassas", "VA", "20110"),
    ("Charlotte", "NC", "28201"), ("Raleigh", "NC", "27601"),
    ("Durham", "NC", "27701"), ("Greensboro", "NC", "27401"),
    ("Baltimore", "MD", "21201"), ("Rockville", "MD", "20850"),
    ("Annapolis", "MD", "21401"), ("Silver Spring", "MD", "20901"),
    ("Washington", "DC", "20001"), ("Bethesda", "MD", "20814"),
    ("Atlanta", "GA", "30301"), ("Savannah", "GA", "31401"),
    ("Charleston", "SC", "29401"), ("Columbia", "SC", "29201"),
    ("Nashville", "TN", "37201"), ("Memphis", "TN", "38101"),
    ("Knoxville", "TN", "37901"), ("Chattanooga", "TN", "37401"),
    ("Louisville", "KY", "40201"), ("Lexington", "KY", "40501"),
    ("Miami", "FL", "33101"), ("Tampa", "FL", "33601"),
    ("Orlando", "FL", "32801"), ("Jacksonville", "FL", "32201"),
]

# ---------------------------------------------------------------------------
# FIRST / LAST NAMES (diverse pool)
# ---------------------------------------------------------------------------
FIRST_NAMES_MALE = [
    "James", "Robert", "Michael", "William", "David", "Richard", "Joseph", "Thomas",
    "Charles", "Christopher", "Daniel", "Matthew", "Anthony", "Donald", "Mark",
    "Paul", "Steven", "Andrew", "Kenneth", "Joshua", "Kevin", "Brian", "George",
    "Timothy", "Ronald", "Edward", "Jason", "Jeffrey", "Ryan", "Jacob",
    "Gary", "Nicholas", "Eric", "Jonathan", "Stephen", "Larry", "Justin",
    "Scott", "Brandon", "Benjamin", "Samuel", "Raymond", "Gregory", "Frank",
    "Alexander", "Patrick", "Jack", "Dennis", "Jerry",
    # Diverse
    "Carlos", "Luis", "Miguel", "Juan", "Antonio", "Jose", "Javier", "Diego",
    "Omar", "Hassan", "Ali", "Mohammed", "Ahmed", "Ibrahim", "Khalid",
    "Wei", "Hiroshi", "Ranjit", "Pradeep", "Vijay", "Amir", "Nishant",
    "Marcus", "DeShawn", "Jamal", "Tyrone", "Andre", "Darius", "Isaiah",
    "Liam", "Noah", "Ethan", "Oliver", "Aiden", "Lucas", "Logan",
    "Theodore", "Sebastian", "Henry", "Owen", "Elijah", "Caleb", "Miles",
]
FIRST_NAMES_FEMALE = [
    "Mary", "Patricia", "Jennifer", "Linda", "Barbara", "Elizabeth", "Susan", "Jessica",
    "Sarah", "Karen", "Lisa", "Nancy", "Betty", "Margaret", "Sandra",
    "Ashley", "Dorothy", "Kimberly", "Emily", "Donna", "Michelle", "Carol",
    "Amanda", "Melissa", "Deborah", "Stephanie", "Rebecca", "Sharon", "Laura",
    "Cynthia", "Kathleen", "Amy", "Angela", "Shirley", "Anna", "Brenda",
    "Pamela", "Emma", "Nicole", "Helen", "Samantha", "Katherine", "Christine",
    "Debra", "Rachel", "Carolyn", "Janet", "Catherine", "Maria", "Heather",
    # Diverse
    "Isabella", "Sofia", "Valentina", "Gabriela", "Camila", "Daniela", "Lucia",
    "Fatima", "Aisha", "Nour", "Zainab", "Leila", "Yasmin",
    "Mei", "Yuki", "Priya", "Ananya", "Shreya", "Deepa", "Riya",
    "Nia", "Zoe", "Aaliyah", "Imani", "Destiny", "Jasmine", "Keisha",
    "Olivia", "Ava", "Mia", "Ella", "Charlotte", "Amelia", "Harper",
    "Evelyn", "Abigail", "Ella", "Grace", "Chloe", "Victoria", "Aurora",
    "Luna", "Penelope", "Lily", "Naomi", "Hannah", "Madeline", "Eleanor",
]
LAST_NAMES = [
    "Smith", "Johnson", "Williams", "Brown", "Jones", "Garcia", "Miller", "Davis",
    "Rodriguez", "Martinez", "Hernandez", "Lopez", "Gonzalez", "Wilson", "Anderson",
    "Thomas", "Taylor", "Moore", "Jackson", "Martin", "Lee", "Perez", "Thompson",
    "White", "Harris", "Sanchez", "Clark", "Ramirez", "Lewis", "Robinson",
    "Walker", "Young", "Allen", "King", "Wright", "Scott", "Torres", "Nguyen",
    "Hill", "Flores", "Green", "Adams", "Nelson", "Baker", "Hall", "Rivera",
    "Campbell", "Mitchell", "Carter", "Roberts", "Patel", "Khan", "Singh",
    "Chen", "Wang", "Li", "Kim", "Park", "Okafor", "Mensah", "Adeyemi",
    "Washington", "Jefferson", "Monroe", "Franklin", "Hamilton", "Brooks",
    "Powell", "Stewart", "Gray", "James", "Watson", "Brooks", "Kelly",
    "Sanders", "Price", "Bennett", "Wood", "Barnes", "Ross", "Henderson",
    "Coleman", "Jenkins", "Perry", "Powell", "Long", "Patterson", "Hughes",
    "Flores", "Washington", "Butler", "Simmons", "Foster", "Gonzales", "Bryant",
    "Alexander", "Russell", "Griffin", "Diaz", "Hayes", "Myers", "Ford",
    "Hamilton", "Graham", "Sullivan", "Wallace", "Woods", "Cole", "West",
    "Jordan", "Owens", "Reynolds", "Fisher", "Ellis", "Harrison", "Gibson",
]
