"""
CareCompanion — AutoHotkey Script Generator
File: utils/ahk_generator.py

Generates valid AHK v1.1 scripts from macro models and dot phrase models.
CareCompanion only generates .ahk files — it never executes them directly.
"""

import re
from datetime import datetime, timezone


# ── Special character escaping for AHK ──

_AHK_SPECIAL = {
    '#': '{#}',
    '!': '{!}',
    '^': '{^}',
    '+': '{+}',
    '{': '{{}',
    '}': '{}}',
}


def escape_ahk_text(text):
    """Escape special AHK characters in raw text for SendInput."""
    result = []
    for ch in text:
        result.append(_AHK_SPECIAL.get(ch, ch))
    return ''.join(result)


def validate_hotkey(hotkey_str):
    """
    Validate a hotkey string is plausible AHK format.
    Returns (is_valid, error_message).
    """
    if not hotkey_str or not hotkey_str.strip():
        return True, ''  # empty hotkey is valid (no binding)

    hotkey = hotkey_str.strip()

    # Basic pattern: optional modifiers (^ ! + #) followed by a key
    pattern = r'^[#!^+]*([a-zA-Z0-9]|F[1-9][0-2]?|Space|Tab|Enter|Escape|Backspace|Delete|Insert|Home|End|PgUp|PgDn|Up|Down|Left|Right|PrintScreen|Pause|NumpadEnter|Numpad[0-9])$'
    if re.match(pattern, hotkey):
        return True, ''

    return False, f'Invalid hotkey format: {hotkey}'


def parse_ahk_hotstring(line):
    """
    Parse an AHK hotstring line like ::abbr::expansion.
    Returns (abbreviation, expansion) tuple or None if not a hotstring.
    """
    line = line.strip()
    # Match ::abbreviation::expansion
    m = re.match(r'^::([^:]+)::(.+)$', line)
    if m:
        return m.group(1).strip(), m.group(2).strip()
    return None


# ── Header block ──

def _header(title, description=''):
    """Generate the standard AHK header comment block."""
    now = datetime.now(timezone.utc).strftime('%Y-%m-%d %H:%M UTC')
    lines = [
        '; ============================================================',
        f'; {title}',
    ]
    if description:
        lines.append(f'; {description}')
    lines += [
        f'; Generated by CareCompanion on {now}',
        '; ============================================================',
        '',
        '#NoEnv',
        '#SingleInstance Force',
        'SetWorkingDir %A_ScriptDir%',
        '',
    ]
    return '\n'.join(lines)


# ── Macro script generation ──

_ACTION_MAP = {
    'click': lambda s: f'Click, {s.target_x}, {s.target_y}',
    'double_click': lambda s: f'Click, 2, {s.target_x}, {s.target_y}',
    'right_click': lambda s: f'Click, Right, {s.target_x}, {s.target_y}',
    'send_keys': lambda s: f'Send, {s.key_sequence}',
    'send_text': lambda s: f'SendInput, {s.key_sequence}',
    'sleep': lambda s: f'Sleep, {s.delay_ms}',
    'mouse_move': lambda s: f'MouseMove, {s.target_x}, {s.target_y}',
    'hotkey': lambda s: f'Send, {s.key_sequence}',
    'window_activate': lambda s: f'WinActivate, {s.window_title}',
}


def _step_to_ahk(step, dot_phrases_by_id=None):
    """Convert a MacroStep to one or more AHK lines."""
    if step.action_type == 'dot_phrase' and dot_phrases_by_id:
        # Inline the expansion from the referenced dot phrase
        # key_sequence holds the dot phrase abbreviation
        for dp in dot_phrases_by_id.values():
            if dp.abbreviation == step.key_sequence:
                return f'SendInput, {escape_ahk_text(dp.expansion)}'
        return f'; [dot_phrase not found: {step.key_sequence}]'

    if step.action_type == 'dot_phrase':
        return f'SendInput, {step.key_sequence}'

    handler = _ACTION_MAP.get(step.action_type)
    if handler:
        return handler(step)

    # Unknown action — emit as comment
    return f'; Unknown action: {step.action_type}'


def generate_macro_script(macro, steps, variables):
    """
    Generate a complete AHK v1 script for a single macro.

    Args:
        macro: AhkMacro model instance
        steps: list of MacroStep instances (ordered by step_order)
        variables: list of MacroVariable instances

    Returns:
        str: Valid AHK v1 script
    """
    parts = [_header(macro.name, macro.description)]

    # If macro has hand-written script content, use it directly
    if macro.script_content and macro.script_content.strip() and not steps:
        if macro.hotkey:
            parts.append(f'{macro.hotkey}::')
            for line in macro.script_content.strip().split('\n'):
                parts.append(f'    {line}')
            parts.append('return')
        else:
            parts.append(macro.script_content.strip())
        return '\n'.join(parts)

    # Step-based macro generation
    if macro.hotkey:
        parts.append(f'{macro.hotkey}::')
        indent = '    '
    else:
        indent = ''

    # Variable input prompts
    for var in variables:
        label = var.var_label or var.var_name
        default = var.default_value or ''
        parts.append(f'{indent}InputBox, {var.var_name}, {label}, Enter {label}:, , 300, 150, , , , , {default}')
        parts.append(f'{indent}if ErrorLevel')
        parts.append(f'{indent}    return')

    # Steps
    for step in steps:
        ahk_line = _step_to_ahk(step)
        if step.comment:
            parts.append(f'{indent}; {step.comment}')
        parts.append(f'{indent}{ahk_line}')
        # Insert delay between steps
        if step.delay_ms and step.action_type != 'sleep':
            parts.append(f'{indent}Sleep, {step.delay_ms}')

    if macro.hotkey:
        parts.append('return')

    return '\n'.join(parts)


def generate_dot_phrase_script(phrases):
    """
    Generate an AHK v1 hotstring file from dot phrases.

    Args:
        phrases: list of DotPhrase model instances

    Returns:
        str: Valid AHK v1 script with hotstring definitions
    """
    parts = [_header('CareCompanion Dot Phrases')]
    parts.append('; Hotstring settings: trigger on any ending character')
    parts.append('#Hotstring EndChars `t `n')
    parts.append('')

    # Group by category
    categories = {}
    for p in phrases:
        categories.setdefault(p.category, []).append(p)

    for cat in sorted(categories.keys()):
        parts.append(f'; --- {cat.upper()} ---')
        for p in categories[cat]:
            expansion = p.expansion

            # Check for placeholders
            placeholders = re.findall(r'\{(\w+)\}', expansion)
            if placeholders:
                # Generate InputBox prompts for each placeholder
                parts.append(f'; {p.abbreviation} — has {len(placeholders)} placeholder(s)')
                parts.append(f'::{p.abbreviation}::')
                unique_ph = list(dict.fromkeys(placeholders))  # preserve order, deduplicate
                for ph in unique_ph:
                    label = ph.replace('_', ' ').title()
                    parts.append(f'    InputBox, {ph}, {label}, Enter {label}:, , 300, 150')
                    parts.append(f'    if ErrorLevel')
                    parts.append(f'        return')
                # Build the expansion with variable substitution
                send_text = expansion
                for ph in unique_ph:
                    send_text = send_text.replace('{' + ph + '}', f'%{ph}%')
                # Multi-line: use SendInput with `n for newlines
                send_text = send_text.replace('\n', '`n')
                parts.append(f'    SendInput, {send_text}')
                parts.append('return')
            else:
                # Simple single-line or multi-line expansion
                if '\n' in expansion:
                    parts.append(f'::{p.abbreviation}::')
                    send_text = expansion.replace('\n', '`n')
                    parts.append(f'    SendInput, {send_text}')
                    parts.append('return')
                else:
                    parts.append(f'::{p.abbreviation}::{expansion}')
        parts.append('')

    return '\n'.join(parts)


def generate_full_library(macros, phrases):
    """
    Generate a combined AHK v1 script with all active macros and dot phrases.

    Args:
        macros: list of (AhkMacro, [MacroStep], [MacroVariable]) tuples
        phrases: list of DotPhrase instances

    Returns:
        str: Complete AHK v1 library script
    """
    parts = [_header('CareCompanion — Full Macro Library')]

    # Macros section
    parts.append('; ============================================================')
    parts.append('; MACROS')
    parts.append('; ============================================================')
    parts.append('')

    for macro, steps, variables in macros:
        parts.append(f'; --- {macro.name} ({macro.category}) ---')
        if macro.script_content and macro.script_content.strip() and not steps:
            # Hand-written script
            if macro.hotkey:
                parts.append(f'{macro.hotkey}::')
                for line in macro.script_content.strip().split('\n'):
                    parts.append(f'    {line}')
                parts.append('return')
            else:
                parts.append(macro.script_content.strip())
        else:
            # Step-based
            if macro.hotkey:
                parts.append(f'{macro.hotkey}::')
                indent = '    '
            else:
                indent = ''

            for var in variables:
                label = var.var_label or var.var_name
                default = var.default_value or ''
                parts.append(f'{indent}InputBox, {var.var_name}, {label}, Enter {label}:, , 300, 150, , , , , {default}')
                parts.append(f'{indent}if ErrorLevel')
                parts.append(f'{indent}    return')

            for step in steps:
                ahk_line = _step_to_ahk(step)
                if step.comment:
                    parts.append(f'{indent}; {step.comment}')
                parts.append(f'{indent}{ahk_line}')
                if step.delay_ms and step.action_type != 'sleep':
                    parts.append(f'{indent}Sleep, {step.delay_ms}')

            if macro.hotkey:
                parts.append('return')
        parts.append('')

    # Dot phrases section
    parts.append('; ============================================================')
    parts.append('; DOT PHRASES (Hotstrings)')
    parts.append('; ============================================================')
    parts.append('')

    dot_phrase_script = generate_dot_phrase_script(phrases)
    # Strip the header from the dot phrase script (we already have one)
    lines = dot_phrase_script.split('\n')
    # Find where the header ends (after the blank line following SetWorkingDir)
    start_idx = 0
    for i, line in enumerate(lines):
        if line.startswith('SetWorkingDir'):
            start_idx = i + 2  # skip the blank line after
            break
    parts.extend(lines[start_idx:])

    return '\n'.join(parts)
